# Generated by Django 6.0.7 on 2026-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
    ]
