# Generated by Django 6.0.7 on 2026-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('general_knowledge', 'General Knowledge'), ('academic', 'Academic'), ('rare_obscure', 'Rare / Obscure')], max_length=20),
        ),
    ]
