EXTRA_4 = [
    ("Abandon", "To leave behind or give up completely.", "They had to ___ the old house after the storm.", ["Keep", "Save", "Preserve"]),
    ("Ability", "The power or skill to do something.", "Her ___ to solve problems impressed everyone.", ["Weakness", "Inability", "Limitation"]),
    ("Absorb", "To take in or soak up gradually.", "The sponge will ___ all the spilled water.", ["Repel", "Release", "Eject"]),
    ("Accept", "To agree to receive something offered.", "She decided to ___ the job offer.", ["Refuse", "Reject", "Decline"]),
    ("Accident", "An unexpected event causing damage or injury.", "The car ___ blocked traffic for hours.", ["Plan", "Intent", "Design"]),
    ("Achieve", "To successfully reach a goal through effort.", "He worked hard to ___ his dreams.", ["Fail", "Quit", "Abandon"]),
    ("Acknowledge", "To accept or admit the existence of something.", "She refused to ___ her mistake.", ["Deny", "Ignore", "Disregard"]),
    ("Acquire", "To gain possession of something.", "The company plans to ___ a new building.", ["Lose", "Give", "Release"]),
    ("Active", "Engaged in action; moving or working.", "The puppy was very ___ all morning.", ["Lazy", "Inactive", "Still"]),
    ("Adapt", "To adjust to new conditions.", "Animals must ___ to survive in the wild.", ["Resist", "Ignore", "Reject"]),
    ("Adequate", "Enough in quantity or quality for a purpose.", "The supply was ___ for the whole trip.", ["Insufficient", "Scarce", "Lacking"]),
    ("Admire", "To regard with respect or warm approval.", "I ___ her dedication to helping others.", ["Despise", "Dislike", "Scorn"]),
    ("Admit", "To confess or acknowledge something.", "He had to ___ that he was wrong.", ["Deny", "Conceal", "Hide"]),
    ("Adopt", "To legally take another's child as one's own.", "They decided to ___ a puppy from the shelter.", ["Reject", "Abandon", "Forsake"]),
    ("Advance", "To move forward or make progress.", "Technology continues to ___ at a rapid pace.", ["Retreat", "Regress", "Recede"]),
    ("Advantage", "A condition giving a greater chance of success.", "Her height gave her an ___ in basketball.", ["Disadvantage", "Drawback", "Hindrance"]),
    ("Adventure", "An exciting or unusual experience.", "They set off on a great ___ through the jungle.", ["Routine", "Boredom", "Monotony"]),
    ("Advise", "To offer suggestions about the best course of action.", "The lawyer will ___ you on your rights.", ["Misguide", "Deceive", "Mislead"]),
    ("Affect", "To have an influence on someone or something.", "The weather can ___ your mood.", ["Ignore", "Neglect", "Disregard"]),
    ("Afford", "To have enough money to pay for something.", "We can finally ___ a new car.", ["Disallow", "Refuse", "Forbid"]),
    ("Agree", "To have the same opinion as someone.", "The committee voted to ___ on the new policy.", ["Differ", "Dispute", "Object"]),
    ("Ahead", "In front of; in a forward direction.", "The finish line is just ___ of us.", ["Behind", "Back", "Rear"]),
    ("Aid", "To provide help or assistance.", "Volunteers came to ___ the flood victims.", ["Hinder", "Obstruct", "Block"]),
    ("Aim", "To point or direct toward a target.", "You should ___ for the center of the target.", ["Miss", "Avoid", "Ignore"]),
    ("Alert", "Quick to notice any unusual or dangerous events.", "The guard remained ___ throughout the night.", ["Drowsy", "Oblivious", "Careless"]),
    ("Allow", "To permit someone to do something.", "Parents should ___ children to explore safely.", ["Forbid", "Prohibit", "Prevent"]),
    ("Alter", "To change or make different.", "We need to ___ our plans for the weather.", ["Keep", "Preserve", "Maintain"]),
    ("Amaze", "To cause great wonder or astonishment.", "The magician's tricks never fail to ___ the crowd.", ["Bore", "Dull", "Disappoint"]),
    ("Ample", "More than enough; plenty of.", "There is ___ space in the backyard for a garden.", ["Scarce", "Limited", "Meager"]),
    ("Ancient", "Very old; belonging to the distant past.", "The ___ ruins dated back thousands of years.", ["Modern", "Recent", "New"]),
    ("Announce", "To make a public declaration about something.", "The principal will ___ the winner at noon.", ["Conceal", "Hide", "Suppress"]),
    ("Annual", "Happening once every year.", "The company held its ___ meeting in March.", ["Occasional", "Rare", "Irregular"]),
    ("Anxious", "Feeling worried or uneasy about something.", "She was ___ before her big presentation.", ["Calm", "Relaxed", "Serene"]),
    ("Apparent", "Clearly visible or understood; obvious.", "It became ___ that he was telling the truth.", ["Unclear", "Hidden", "Vague"]),
    ("Appeal", "To make a serious or urgent request.", "The charity will ___ for donations this weekend.", ["Refuse", "Deny", "Reject"]),
    ("Applaud", "To show approval by clapping hands.", "The audience rose to ___ the performers.", ["Boo", "Criticize", "Hiss"]),
    ("Apply", "To make a formal request for something.", "She decided to ___ for the scholarship.", ["Reject", "Withdraw", "Ignore"]),
    ("Appoint", "To assign a job or role to someone.", "The board will ___ a new director next week.", ["Dismiss", "Fire", "Remove"]),
    ("Appreciate", "To recognize the value or significance of something.", "I ___ all the help you have given me.", ["Disregard", "Underrate", "Ignore"]),
    ("Approach", "To come near to something in distance or time.", "The train began to ___ the station.", ["Retreat", "Avoid", "Leave"]),
    ("Approve", "To officially agree to or accept something.", "The committee voted to ___ the proposal.", ["Reject", "Veto", "Deny"]),
    ("Argue", "To exchange conflicting views; to debate.", "They ___ about politics all the time.", ["Agree", "Concur", "Harmonize"]),
    ("Arise", "To emerge or come into existence.", "New challenges ___ every day in the business world.", ["Disappear", "Vanish", "Subside"]),
    ("Arrange", "To put things in a neat or required order.", "She will ___ the chairs for the ceremony.", ["Jumble", "Scatter", "Mess"]),
    ("Arrest", "To seize someone by legal authority.", "The police will ___ the suspect tomorrow.", ["Free", "Release", "Liberate"]),
    ("Arrive", "To reach a destination.", "What time will you ___ at the airport?", ["Depart", "Leave", "Go"]),
    ("Article", "A piece of writing in a publication.", "She wrote an interesting ___ about climate change.", ["Book", "Chapter", "Volume"]),
    ("Assist", "To give help or support to someone.", "The nurse will ___ the doctor during surgery.", ["Hinder", "Obstruct", "Harm"]),
    ("Assume", "To suppose something without proof.", "I ___ you have already eaten lunch.", ["Know", "Confirm", "Verify"]),
    ("Assure", "To tell someone something positively to remove doubt.", "I ___ you that the package will arrive tomorrow.", ["Doubt", "Question", "Distrust"]),
    ("Attach", "To fasten or join one thing to another.", "Please ___ the file to your email.", ["Detach", "Separate", "Remove"]),
    ("Attempt", "To try to do something.", "She will ___ to break the world record.", ["Abandon", "Quit", "Neglect"]),
    ("Attend", "To be present at an event or function.", "Will you ___ the meeting tomorrow?", ["Miss", "Skip", "Absent"]),
    ("Attract", "To draw or pull something toward oneself.", "Bright colors ___ butterflies to the garden.", ["Repel", "Deter", "Discourage"]),
    ("Auction", "A public sale where items are sold to the highest bidder.", "The painting was sold at ___ for a record price.", ["Gift", "Trade", "Barter"]),
    ("Authentic", "Genuine and original; not fake.", "The museum displays ___ artifacts from Ancient Egypt.", ["Fake", "Forged", "Counterfeit"]),
    ("Average", "Typical or normal in standard.", "The ___ temperature in July is 85 degrees.", ["Exceptional", "Extreme", "Unusual"]),
    ("Avoid", "To stay away from something.", "You should ___ eating too much sugar.", ["Face", "Confront", "Seek"]),
    ("Award", "A prize given for achievement.", "She received an ___ for her volunteer work.", ["Penalty", "Fine", "Punishment"]),
    ("Aware", "Having knowledge or perception of something.", "He was ___ of the risks involved.", ["Ignorant", "Unaware", "Oblivious"]),
    ("Awful", "Very bad or unpleasant.", "The weather was ___ during our vacation.", ["Wonderful", "Pleasant", "Delightful"]),
    ("Awkward", "Lacking grace or skill; clumsy.", "His ___ silence made everyone uncomfortable.", ["Graceful", "Smooth", "Elegant"]),
    ("Balance", "An even distribution of weight enabling stability.", "She kept her ___ on the tightrope with practice.", ["Imbalance", "Instability", "Unsteadiness"]),
    ("Bald", "Having little or no hair on the head.", "He started going ___ in his thirties.", ["Hairy", "Furry", "Shaggy"]),
    ("Ban", "To officially prohibit or forbid something.", "The school decided to ___ cell phones in class.", ["Allow", "Permit", "Approve"]),
    ("Banner", "A long strip of cloth bearing a slogan or design.", "The ___ hung above the entrance to the stadium.", ["Poster", "Flag", "Sign"]),
    ("Bar", "A long rod or rigid piece of metal or wood.", "He used an iron ___ to pry open the crate.", ["Opening", "Gap", "Hole"]),
    ("Bare", "Without covering or clothing; naked.", "The walls were ___ after we removed the paintings.", ["Covered", "Clothed", "Adorned"]),
    ("Bargain", "An agreement between parties about what each will give.", "They struck a ___ to share the profits equally.", ["Rip-off", "Overcharge", "Swindle"]),
    ("Barrier", "A fence or obstacle that prevents movement or access.", "The mountain range formed a natural ___ between the regions.", ["Opening", "Passage", "Gateway"]),
    ("Bashful", "Shy and easily embarrassed.", "The ___ child hid behind his mother's skirt.", ["Bold", "Outgoing", "Confident"]),
    ("Battle", "A sustained fight between armed forces.", "The ___ lasted for three bloody days.", ["Truce", "Peace", "Armistice"]),
    ("Beam", "A long sturdy piece of wood or metal used in building.", "The wooden ___ supported the ceiling for centuries.", ["Column", "Post", "Pillar"]),
    ("Bear", "To carry or endure a burden.", "The bridge can ___ the weight of heavy trucks.", ["Avoid", "Shirk", "Dodge"]),
    ("Beast", "A large or dangerous animal.", "The mythical ___ terrorized the village for years.", ["Pet", "Companion", "Friend"]),
    ("Behave", "To act or conduct oneself in a specified way.", "The children were told to ___ during the ceremony.", ["Misbehave", "Act up", "Disobey"]),
    ("Belief", "An acceptance that something is true or exists.", "His ___ in hard work helped him succeed.", ["Doubt", "Disbelief", "Skepticism"]),
    ("Belong", "To be a member or part of a group.", "These books ___ on the top shelf.", ["Exclude", "Omit", "Separate"]),
    ("Beneath", "Underneath or below something.", "The cat hid ___ the bed during the storm.", ["Above", "Over", "Beyond"]),
    ("Benefit", "An advantage or profit gained from something.", "Regular exercise has many health ___.", ["Drawback", "Disadvantage", "Harm"]),
    ("Betray", "To be disloyal or treacherous to someone.", "He would never ___ his friend's trust.", ["Protect", "Defend", "Support"]),
    ("Beyond", "At or to the further side of something.", "The mountains stretched ___ the horizon.", ["Within", "Inside", "Near"]),
    ("Bid", "To offer a certain price for something at an auction.", "She decided to ___ on the antique vase.", ["Sell", "Refuse", "Withdraw"]),
    ("Bitter", "Sharp or harsh in taste, smell, or attitude.", "The ___ cold wind made everyone shiver.", ["Sweet", "Pleasant", "Mild"]),
    ("Blame", "To hold someone responsible for a fault or wrong.", "Do not ___ others for your own mistakes.", ["Praise", "Credit", "Acclaim"]),
    ("Blank", "Empty or without writing or marks.", "His mind went ___ during the exam.", ["Full", "Complete", "Written"]),
    ("Blast", "A destructive wave of air from an explosion.", "The ___ shattered windows across the street.", ["Implosion", "Vacuum", "Suck"]),
    ("Bleak", "Cold, harsh, and without any pleasant features.", "The landscape looked ___ under the gray sky.", ["Cheerful", "Bright", "Inviting"]),
    ("Blend", "To mix different substances together.", "She used a blender to ___ the fruits.", ["Separate", "Divide", "Isolate"]),
    ("Bless", "To confer divine favor or protection upon.", "The priest will ___ the new church building.", ["Curse", "Damn", "Condemn"]),
    ("Blind", "Unable to see; lacking sight.", "The ___ man navigated using his walking stick.", ["Sighted", "Aware", "Perceptive"]),
    ("Bliss", "Perfect happiness or great joy.", "The newlyweds were in a state of pure ___.", ["Misery", "Anguish", "Sorrow"]),
    ("Block", "To obstruct or prevent movement or progress.", "Protesters tried to ___ the entrance to the building.", ["Clear", "Unblock", "Open"]),
    ("Bloom", "To produce flowers; to flourish.", "The roses will ___ in the spring.", ["Wilt", "Fade", "Shrivel"]),
    ("Blunder", "A careless or stupid mistake.", "Missing the flight was a huge ___.", ["Success", "Triumph", "Victory"]),
    ("Blunt", "Not sharp; having a dull edge or point.", "The knife was too ___ to cut through the rope.", ["Sharp", "Pointed", "Keen"]),
    ("Blush", "To become red in the face from shyness or embarrassment.", "She began to ___ when he complimented her.", ["Pale", "Whiten", "Fade"]),
    ("Boast", "To talk with excessive pride about oneself.", "He likes to ___ about his accomplishments.", ["Humble", "Modest", "Understate"]),
    ("Bold", "Showing a willingness to take risks; courageous.", "The ___ explorer ventured into the unknown jungle.", ["Timid", "Cowardly", "Meek"]),
    ("Bond", "A connection or link between people or things.", "The shared experience created a strong ___ between them.", ["Separation", "Division", "Rift"]),
    ("Bonus", "An extra payment beyond what is usual.", "All employees received a holiday ___ this year.", ["Penalty", "Fine", "Deduction"]),
    ("Border", "The line separating two political or geographical areas.", "They crossed the ___ into Canada at midnight.", ["Interior", "Center", "Middle"]),
    ("Bother", "To take the trouble to do something.", "Don't ___ coming if you are too tired.", ["Help", "Aid", "Assist"]),
    ("Bounce", "To spring back after hitting a surface.", "The ball will ___ high on concrete.", ["Stick", "Stop", "Absorb"]),
    ("Bound", "To leap or jump; to move with great energy.", "The deer ___ed across the open field.", ["Crawl", "Creep", "Trudge"]),
    ("Brave", "Showing courage in the face of danger or pain.", "The ___ firefighter rescued the trapped family.", ["Cowardly", "Timid", "Fearful"]),
    ("Brawl", "A rough or noisy fight.", "The ___ started outside the bar late at night.", ["Truce", "Peace", "Harmony"]),
    ("Breach", "A gap or break in something, especially a wall or barrier.", "Water poured through the ___ in the dam.", ["Seal", "Block", "Wall"]),
    ("Breeze", "A gentle wind.", "A cool ___ came through the open window.", ["Gale", "Storm", "Hurricane"]),
    ("Bribe", "To dishonestly give money or favors to influence behavior.", "He tried to ___ the official for a permit.", ["Reward", "Compensate", "Pay"]),
    ("Bridle", "To show anger or resentment; to restrain.", "She could not ___ her frustration any longer.", ["Release", "Free", "Unleash"]),
    ("Brief", "Short in duration or length.", "The meeting was ___ and productive.", ["Long", "Extended", "Prolonged"]),
    ("Bright", "Giving out or reflecting much light; shining.", "The ___ sun made everyone squint.", ["Dark", "Dull", "Dim"]),
    ("Brisk", "Quick and energetic; lively.", "They took a ___ walk through the park.", ["Slow", "Sluggish", "Lazy"]),
    ("Brittle", "Hard but easily broken or shattered.", "The old plastic had become ___ and cracked.", ["Flexible", "Supple", "Durable"]),
    ("Broad", "Having a wide extent from side to side.", "The river was ___ and slow-moving.", ["Narrow", "Tight", "Slim"]),
    ("Brochure", "A small book or magazine containing pictures and information.", "The travel ___ showed beautiful beach resorts.", ["Manual", "Report", "Novel"]),
    ("Bruise", "An injury appearing as a purple mark on the skin.", "He got a ___ from falling off his bike.", ["Bandage", "Heal", "Cure"]),
    ("Brutal", "Savage and cruel; extremely harsh.", "The ___ winter lasted for five months.", ["Gentle", "Kind", "Mild"]),
    ("Bubble", "A thin sphere of liquid enclosing air or gas.", "The child blew a ___ with her gum.", ["Solid", "Mass", "Block"]),
    ("Bucket", "A cylindrical open container with a handle.", "She filled the ___ with water from the well.", ["Cup", "Glass", "Bottle"]),
    ("Buddy", "A close friend or companion.", "He and his ___ go fishing every weekend.", ["Stranger", "Rival", "Enemy"]),
    ("Budget", "An estimate of income and expenditure for a set period.", "We need to plan our ___ carefully this month.", ["Surplus", "Wealth", "Profit"]),
    ("Bulge", "To swell or protrude outward.", "The bag began to ___ from all the groceries inside.", ["Deflate", "Shrink", "Flatten"]),
    ("Bulky", "Taking up much space; large and unwieldy.", "The ___ sofa barely fit through the doorway.", ["Compact", "Small", "Tiny"]),
    ("Bullet", "A projectile fired from a gun.", "The ___ whizzed past his ear.", ["Missile", "Rocket", "Shell"]),
    ("Bully", "A person who uses strength to intimidate others.", "The school took action against the ___.", ["Friend", "Ally", "Protector"]),
    ("Bunch", "A number of things grouped or fastened together.", "She bought a ___ of bananas at the market.", ["Single", "One", "Individual"]),
    ("Burden", "A heavy load or responsibility.", "The ___ of caring for her parents fell on her.", ["Relief", "Ease", "Freedom"]),
    ("Burst", "To break open or apart suddenly.", "The pipe will ___ if the water freezes.", ["Mend", "Fix", "Seal"]),
    ("Bustle", "To move in a hurried or energetic way.", "People ___d around the busy market square.", ["Linger", "Dawdle", "Loiter"]),
    ("Busy", "Having a great deal to do; occupied.", "She was too ___ to answer the phone.", ["Idle", "Free", "Inactive"]),
    ("Buxom", "Full-figured and curvaceous; plump and healthy-looking.", "The ___ woman had a cheerful, rosy complexion.", ["Gaunt", "Bony", "Slender"]),
    ("Cable", "A thick wire for transmitting electricity or signals.", "The internet ___ was damaged in the storm.", ["Wireless", "Radio", "Antenna"]),
    ("Calamity", "An event causing great damage or distress.", "The flood was a ___ that devastated the town.", ["Blessing", "Fortune", "Miracle"]),
    ("Calculate", "To determine mathematically.", "She used a calculator to ___ the total cost.", ["Guess", "Estimate", "Assume"]),
    ("Calm", "Not showing or feeling nervousness or agitation.", "She remained ___ during the emergency.", ["Panicked", "Agitated", "Frantic"]),
    ("Cancel", "To decide that something planned will not happen.", "They had to ___ the picnic due to rain.", ["Confirm", "Schedule", "Arrange"]),
    ("Candid", "Truthful and straightforward; honest.", "He gave a ___ interview about his struggles.", ["Deceptive", "Evasive", "Dishonest"]),
    ("Capable", "Having the ability or skill to do something.", "She is a ___ and experienced manager.", ["Incompetent", "Unable", "Inept"]),
    ("Capacity", "The maximum amount something can hold.", "The stadium has a ___ of fifty thousand.", ["Limit", "Restriction", "Maximum"]),
    ("Capital", "The most important city of a country or region.", "London is the ___ of England.", ["Rural", "Suburb", "Village"]),
    ("Capture", "To take into possession by force.", "The soldiers tried to ___ the enemy fort.", ["Release", "Free", "Liberate"]),
    ("Careless", "Not giving sufficient attention to avoid mistakes.", "His ___ driving caused the accident.", ["Careful", "Cautious", "Attentive"]),
    ("Carve", "To cut into a surface to create a design.", "He learned to ___ wood into beautiful sculptures.", ["Melt", "Smooth", "Reshape"]),
    ("Castle", "A large fortified building from medieval times.", "The ___ stood on the hill for centuries.", ["Cottage", "Hut", "Cabin"]),
    ("Casual", "Relaxed and unconcerned; informal.", "They wore ___ clothes to the barbecue.", ["Formal", "Dressy", "Official"]),
    ("Catalog", "A complete list of items arranged systematically.", "The library ___ helps you find any book.", ["Inventory", "Log", "Index"]),
    ("Catastrophe", "A sudden and widespread disaster.", "The earthquake was a ___ that leveled the city.", ["Triumph", "Success", "Victory"]),
    ("Cautious", "Being careful to avoid potential dangers.", "The driver was ___ on the icy road.", ["Reckless", "Rash", "Bold"]),
    ("Cease", "To come to an end or bring to an end.", "The company will ___ operations next month.", ["Continue", "Persist", "Prolong"]),
    ("Celebrate", "To mark a special occasion with festivities.", "We will ___ your birthday with a surprise party.", ["Mourn", "Lament", "Ignore"]),
    ("Census", "An official count of a population.", "The government conducts a ___ every ten years.", ["Estimate", "Guess", "Survey"]),
    ("Central", "At the center of something; most important.", "The ___ bank controls the nation's money supply.", ["Peripheral", "Outer", "Edge"]),
    ("Ceremony", "A formal event performed on a special occasion.", "The wedding ___ was held in the garden.", ["Informality", "Casualness", "Chaos"]),
    ("Certain", "Known for sure; established beyond doubt.", "Are you ___ you locked the door?", ["Uncertain", "Doubtful", "Unsure"]),
    ("Chafe", "To irritate or rub the skin sore.", "The rough collar began to ___ his neck.", ["Soothe", "Comfort", "Ease"]),
    ("Chain", "A series of connected metal rings used for fastening.", "The dog was secured with a heavy ___.", ["Link", "Bond", "Connection"]),
    ("Challenge", "A task or situation that tests someone's abilities.", "Climbing the mountain was a huge ___.", ["Ease", "Simplicity", "Facility"]),
    ("Champion", "A person who has defeated all opponents in a contest.", "The ___ raised the trophy above his head.", ["Loser", "Underdog", "Novice"]),
    ("Chance", "The possibility of something happening.", "There is a good ___ of rain tomorrow.", ["Certainty", "Surety", "Guarantee"]),
    ("Change", "To make or become different.", "People often resist ___ even when it is good.", ["Stagnate", "Persist", "Remain"]),
    ("Chaos", "Complete disorder and confusion.", "The room was in total ___ after the party.", ["Order", "Organization", "System"]),
    ("Chapter", "A main division of a book.", "The first ___ of the book was very exciting.", ["Volume", "Edition", "Installment"]),
    ("Character", "The mental and moral qualities of an individual.", "Her strong ___ helped her overcome adversity.", ["Weakness", "Flaw", "Vice"]),
    ("Charge", "To ask for a price for goods or services.", "How much do they ___ for a haircut?", ["Free", "Complimentary", "Gratis"]),
    ("Charity", "The voluntary giving of help to those in need.", "She donates to ___ every month.", ["Greed", "Selfishness", "Stinginess"]),
    ("Charm", "The power or quality of delighting or fascinating others.", "Her natural ___ won over the entire audience.", ["Repulsion", "Ugliness", "Rudeness"]),
    ("Chase", "To pursue in order to catch.", "The cat likes to ___ mice in the garden.", ["Flee", "Avoid", "Escape"]),
    ("Cheap", "Low in price; costing little.", "The ___ tickets sold out within minutes.", ["Expensive", "Costly", "Pricey"]),
    ("Cheat", "To act dishonestly to gain an advantage.", "Students who ___ will be expelled.", ["Play fair", "Be honest", "Respect"]),
    ("Check", "To examine something to verify its condition.", "Please ___ your work for errors before submitting.", ["Ignore", "Neglect", "Overlook"]),
    ("Cheer", "To shout encouragement or approval.", "The crowd began to ___ when the team scored.", ["Boo", "Jeer", "Hiss"]),
    ("Cherish", "To protect and care for something lovingly.", "I will always ___ the memories of my childhood.", ["Neglect", "Abandon", "Ignore"]),
    ("Chew", "To grind food with the teeth.", "You should ___ your food thoroughly before swallowing.", ["Gulp", "Swallow", "Devour"]),
    ("Chief", "A leader or ruler of a group.", "The tribal ___ made decisions for his people.", ["Follower", "Subordinate", "Member"]),
    ("Chill", "An unpleasant feeling of coldness.", "The morning ___ made us reach for our jackets.", ["Warmth", "Heat", "Toastiness"]),
    ("Choke", "To prevent from breathing by blocking the windpipe.", "He began to ___ on a piece of food.", ["Breathe", "Inhale", "Respire"]),
    ("Choose", "To pick out or select from a number of options.", "You must ___ which color you prefer.", ["Reject", "Refuse", "Dismiss"]),
    ("Chop", "To cut into pieces with a sharp tool.", "She used a knife to ___ the vegetables.", ["Slice", "Dice", "Mince"]),
    ("Circuit", "A roughly circular line, route, or movement.", "The race ___ wound through the hills.", ["Line", "Path", "Straight"]),
    ("Circular", "Having the shape of a circle.", "The table was large and ___ in shape.", ["Square", "Triangular", "Rectangular"]),
    ("Citizen", "A legally recognized subject of a country.", "Every ___ has the right to vote.", ["Foreigner", "Alien", "Visitor"]),
    ("Civil", "Relating to ordinary citizens and their concerns.", "The ___ war divided the nation.", ["Military", "Uncivil", "Rude"]),
    ("Claim", "To state or assert that something is true.", "She ___s to have seen the missing cat.", ["Deny", "Dispute", "Refute"]),
    ("Clap", "To strike the palms together as a show of approval.", "The audience began to ___ after the speech.", ["Silence", "Quiet", "Hush"]),
    ("Clash", "A conflict or violent confrontation.", "The two armies were on the verge of a ___.", ["Truce", "Peace", "Alliance"]),
    ("Classic", "Something of the highest quality and enduring value.", "That movie is a ___ that never gets old.", ["Modern", "Recent", "Contemporary"]),
    ("Clause", "A distinct part of a sentence or legal document.", "The contract includes a ___ about termination.", ["Phrase", "Word", "Sentence"]),
    ("Clean", "Free from dirt, marks, or stains.", "The kitchen was spotlessly ___ after the cleanup.", ["Dirty", "Filthy", "Grimy"]),
    ("Clear", "Easy to see, hear, or understand.", "The instructions were ___ and easy to follow.", ["Vague", "Unclear", "Confusing"]),
    ("Clever", "Quick to understand, learn, and devise ideas.", "The ___ student solved the puzzle in minutes.", ["Dull", "Stupid", "Slow"]),
    ("Climate", "The weather conditions prevailing in an area.", "The ___ in the tropics is warm and humid.", ["Weather", "Forecast", "Atmosphere"]),
    ("Climb", "To go up something using hands and feet.", "They began to ___ the steep mountain trail.", ["Descend", "Drop", "Fall"]),
    ("Cling", "To hold tightly to something.", "The child would ___ to her mother's hand.", ["Release", "Let go", "Free"]),
    ("Clinic", "A place where medical treatment is given.", "He went to the ___ for his annual checkup.", ["Hospital", "Surgery", "Ward"]),
    ("Cloak", "A loose outer garment that covers the body.", "She wore a heavy ___ in the cold rain.", ["Jacket", "Coat", "Vest"]),
    ("Clumsy", "Moving or handling things in an awkward way.", "The ___ waiter spilled water on the table.", ["Graceful", "Elegant", "Adept"]),
    ("Cluster", "A group of similar things positioned close together.", "A ___ of stars shone brightly in the sky.", ["Single", "Individual", "Alone"]),
    ("Clutch", "To grasp or hold tightly.", "She had to ___ the railing to keep from falling.", ["Release", "Drop", "Free"]),
    ("Coarse", "Rough or harsh in texture.", "The ___ fabric irritated his sensitive skin.", ["Smooth", "Soft", "Fine"]),
    ("Coast", "The land near a shoreline.", "They drove along the ___ with the windows down.", ["Inland", "Interior", "Center"]),
    ("Code", "A system of words or symbols used for secrecy.", "The spy sent messages in a secret ___.", ["Plaintext", "Clear", "Open"]),
    ("Coil", "To wind into a series of loops.", "The snake began to ___ before it struck.", ["Uncoil", "Straighten", "Unwind"]),
    ("Coin", "A flat piece of metal used as money.", "He flipped a ___ to make the decision.", ["Bill", "Note", "Paper"]),
    ("Collapse", "To fall down or give way suddenly.", "The old building was about to ___.", ["Stand", "Rise", "Strengthen"]),
    ("Collect", "To gather together from a number of sources.", "She likes to ___ stamps from different countries.", ["Scatter", "Disperse", "Distribute"]),
    ("Colony", "A group of people settling in a new territory.", "The ___ was established in the early 1600s.", ["Homeland", "Native land", "Motherland"]),
    ("Column", "A tall vertical structure used as a support.", "The marble ___s lined the entrance to the temple.", ["Beam", "Rafter", "Joist"]),
    ("Combat", "Fighting between armed forces.", "The soldiers were trained for ___.", ["Peace", "Truce", "Harmony"]),
    ("Combine", "To join or merge together.", "We should ___ our resources for the project.", ["Separate", "Divide", "Split"]),
    ("Comedy", "Entertainment intended to make people laugh.", "The ___ show had everyone in stitches.", ["Tragedy", "Drama", "Horror"]),
    ("Comfort", "A state of physical ease and freedom from pain.", "She found ___ in her friend's warm embrace.", ["Discomfort", "Pain", "Distress"]),
    ("Command", "To give an authoritative order.", "The general will ___ the troops into battle.", ["Obey", "Submit", "Comply"]),
    ("Comment", "A verbal or written remark expressing an opinion.", "He made a rude ___ about her outfit.", ["Silence", "Quiet", "Muteness"]),
    ("Commit", "To pledge or dedicate oneself to something.", "She decided to ___ to the marathon training.", ["Abandon", "Renounce", "Quit"]),
    ("Common", "Occurring or appearing frequently; ordinary.", "Colds are a ___ illness in winter.", ["Rare", "Uncommon", "Unique"]),
    ("Communicate", "To share information by speaking or writing.", "It is important to ___ clearly with your team.", ["Conceal", "Hide", "Suppress"]),
    ("Community", "A group of people living in the same place.", "The ___ rallied together after the disaster.", ["Individual", "Alone", "Isolation"]),
    ("Compact", "Closely and neatly packed together; small.", "The ___ apartment had everything she needed.", ["Spacious", "Roomie", "Expansive"]),
    ("Compare", "To examine similarities and differences.", "You cannot ___ apples and oranges.", ["Contrast", "Distinguish", "Separate"]),
    ("Compel", "To force or oblige someone to do something.", "The law will ___ companies to disclose information.", ["Persuade", "Coax", "Encourage"]),
    ("Compete", "To strive against others to win.", "Athletes from around the world ___ in the Olympics.", ["Cooperate", "Collaborate", "Work together"]),
    ("Complain", "To express dissatisfaction or annoyance.", "Customers often ___ about the long wait times.", ["Praise", "Commend", "Applaud"]),
    ("Complete", "Having all parts; finished.", "The project is finally ___ after months of work.", ["Incomplete", "Partial", "Unfinished"]),
    ("Complex", "Consisting of many different parts; complicated.", "The ___ machine required expert maintenance.", ["Simple", "Basic", "Straightforward"]),
    ("Complicate", "To make something more difficult or complex.", "Please do not ___ things with unnecessary rules.", ["Simplify", "Clarify", "Streamline"]),
    ("Comply", "To act in accordance with a rule or request.", "All employees must ___ with safety regulations.", ["Defy", "Disobey", "Violate"]),
    ("Component", "A part or element of a larger whole.", "Each ___ of the engine must function correctly.", ["Whole", "Entirety", "Total"]),
    ("Compose", "To write or create something.", "She began to ___ music at a very young age.", ["Destroy", "Demolish", "Ruin"]),
    ("Compound", "A mixture of two or more elements or parts.", "The chemical ___ was highly unstable.", ["Element", "Single", "Pure"]),
    ("Comprehend", "To understand something fully.", "It was difficult to ___ the complexity of the theory.", ["Misunderstand", "Confuse", "Ignore"]),
    ("Compress", "To squeeze or press together.", "The machine will ___ the trash into small bales.", ["Expand", "Inflate", "Stretch"]),
    ("Compute", "To calculate or determine mathematically.", "The computer can ___ millions of operations per second.", ["Guess", "Estimate", "Approximate"]),
    ("Conceal", "To hide or keep something secret.", "He tried to ___ his disappointment with a smile.", ["Reveal", "Disclose", "Show"]),
    ("Concede", "To admit that something is true after denying it.", "He had to ___ that he was wrong.", ["Deny", "Dispute", "Contradict"]),
    ("Concentrate", "To focus all attention on something.", "You need to ___ on your studies.", ["Distract", "Ignore", "Neglect"]),
    ("Concept", "An abstract idea or general notion.", "The ___ of time is difficult to define.", ["Reality", "Object", "Thing"]),
    ("Concern", "A matter of interest or importance.", "The safety of the children is our main ___.", ["Unconcern", "Indifference", "Apathy"]),
    ("Conclude", "To bring something to an end.", "Let us ___ the meeting with a summary.", ["Begin", "Start", "Open"]),
    ("Concrete", "Existing in a material form; not abstract.", "We need ___ evidence to prove the case.", ["Abstract", "Vague", "Theoretical"]),
    ("Condemn", "To express complete disapproval of something.", "The court will ___ the criminal to prison.", ["Praise", "Acclaim", "Applaud"]),
    ("Condition", "The state of something regarding its quality.", "The car was in excellent ___ for its age.", ["Repair", "Fix", "Mend"]),
    ("Conduct", "To organize and carry out an activity.", "The scientist will ___ an experiment tomorrow.", ["Mismanage", "Botch", "Ignore"]),
    ("Confess", "To admit to a crime or wrongdoing.", "The suspect finally decided to ___.", ["Deny", "Conceal", "Hide"]),
    ("Confidence", "A feeling of self-assurance from one's abilities.", "Her ___ grew with each successful presentation.", ["Doubt", "Insecurity", "Timidity"]),
    ("Confirm", "To establish the truth or correctness of something.", "Please ___ your reservation by Friday.", ["Deny", "Disprove", "Refute"]),
    ("Conflict", "A serious disagreement or argument.", "The ___ between the two countries escalated.", ["Peace", "Harmony", "Agreement"]),
    ("Conform", "To behave according to accepted standards.", "Students are expected to ___ to the school rules.", ["Rebel", "Differ", "Deviate"]),
    ("Confront", "To face in hostility or defiance.", "She decided to ___ her fears directly.", ["Avoid", "Evade", "Dodge"]),
    ("Confuse", "To make someone unable to think clearly.", "The complicated instructions only served to ___ him.", ["Clarify", "Explain", "Enlighten"]),
    ("Connect", "To join together or link.", "The bridge will ___ the two islands.", ["Separate", "Disconnect", "Divide"]),
    ("Conscience", "An inner sense of right and wrong.", "His ___ would not let him remain silent.", ["Guilt", "Shame", "Regret"]),
    ("Conscious", "Aware of and responding to one's surroundings.", "He was ___ of the danger he faced.", ["Unaware", "Oblivious", "Unconscious"]),
    ("Consent", "Permission for something to happen.", "She gave her ___ for the medical procedure.", ["Refusal", "Denial", "Objection"]),
    ("Consequence", "A result or effect of an action.", "Every action has a ___.", ["Cause", "Source", "Origin"]),
    ("Consider", "To think carefully about something.", "Please ___ all the options before deciding.", ["Dismiss", "Ignore", "Reject"]),
    ("Consist", "To be composed or made up of something.", "The team will ___ of five members.", ["Exclude", "Omit", "Lack"]),
    ("Constant", "Occurring continuously; never stopping.", "The ___ noise from the construction was annoying.", ["Variable", "Intermittent", "Irregular"]),
    ("Construct", "To build or put together.", "The workers will ___ a new bridge over the river.", ["Demolish", "Destroy", "Dismantle"]),
    ("Consult", "To seek advice or information from someone.", "You should ___ a doctor if symptoms persist.", ["Ignore", "Disregard", "Neglect"]),
    ("Consume", "To eat, drink, or use up.", "The fire quickly ___d the dry forest.", ["Preserve", "Save", "Conserve"]),
    ("Contact", "To get in touch with someone.", "Please ___ us if you have any questions.", ["Ignore", "Avoid", "Neglect"]),
    ("Contain", "To hold or have within.", "The box ___s twelve chocolate bars.", ["Exclude", "Release", "Empty"]),
    ("Contemporary", "Living or occurring in the present.", "The museum features ___ art from around the world.", ["Old", "Antique", "Vintage"]),
    ("Contend", "To struggle or compete to overcome something.", "The team had to ___ with many injuries.", ["Yield", "Surrender", "Submit"]),
    ("Contest", "A competition for a prize.", "She won first place in the spelling ___.", ["Cooperation", "Collaboration", "Agreement"]),
    ("Continue", "To keep doing something without stopping.", "Please ___ with your work.", ["Stop", "Cease", "Pause"]),
    ("Contract", "A written or spoken agreement.", "They signed a ___ for the sale of the house.", ["Breach", "Violation", "Disagreement"]),
    ("Contrast", "The state of being strikingly different.", "The ___ between the rich and poor was stark.", ["Similarity", "Sameness", "Resemblance"]),
    ("Contribute", "To give something to a common cause.", "Everyone should ___ to the team effort.", ["Withhold", "Keep", "Retain"]),
    ("Control", "The power to influence or direct behavior.", "The pilot maintained ___ of the aircraft.", ["Powerlessness", "Submission", "Weakness"]),
    ("Controversy", "A prolonged public disagreement.", "The decision sparked ___ among the community.", ["Agreement", "Consensus", "Harmony"]),
    ("Convenient", "Easy to use or suitable for a purpose.", "The location is ___ for public transportation.", ["Inconvenient", "Awkward", "Difficult"]),
    ("Convention", "A large formal meeting or assembly.", "The annual ___ attracts thousands of visitors.", ["Individual", "Solo", "One"]),
    ("Convince", "To cause someone to believe something firmly.", "She tried to ___ him to change his mind.", ["Dissuade", "Discourage", "Deter"]),
    ("Cook", "To prepare food by heating it.", "She loves to ___ Italian cuisine for her family.", ["Serve", "Eat", "Devour"]),
    ("Cool", "Of or at a fairly low temperature.", "The ___ water was refreshing on a hot day.", ["Warm", "Hot", "Heated"]),
    ("Cooperate", "To work together toward a common goal.", "The two companies decided to ___ on the project.", ["Conflict", "Compete", "Oppose"]),
    ("Cope", "To deal effectively with something difficult.", "She learned to ___ with stress through meditation.", ["Succumb", "Yield", "Surrender"]),
    ("Copy", "To make something identical to another.", "Please ___ the document for all attendees.", ["Original", "Create", "Innovate"]),
    ("Core", "The central or most important part.", "The ___ of the problem is lack of funding.", ["Surface", "Exterior", "Outer"]),
    ("Correct", "Without error; accurate.", "Your answer was ___ on all counts.", ["Wrong", "Incorrect", "False"]),
    ("Correspond", "To be consistent or compatible with something.", "The witness's account does not ___ with the facts.", ["Differ", "Contradict", "Disagree"]),
    ("Corrupt", "Dishonest or morally depraved.", "The ___ official was arrested for bribery.", ["Honest", "Upright", "Ethical"]),
    ("Costly", "Expensive; costing a great deal.", "The lawsuit was a ___ mistake for the company.", ["Cheap", "Inexpensive", "Affordable"]),
    ("Cottage", "A small house, typically in the countryside.", "They rented a cozy ___ by the lake.", ["Mansion", "Castle", "Estate"]),
    ("Couch", "A long upholstered seat for two or more people.", "She curled up on the ___ to read a book.", ["Chair", "Stool", "Bench"]),
    ("Counsel", "To give advice to someone.", "The therapist will ___ the grieving family.", ["Misguide", "Mislead", "Harm"]),
    ("Count", "To determine the total number of something.", "Please ___ the number of chairs in the room.", ["Estimate", "Guess", "Approximate"]),
    ("Counter", "To respond to an attack or criticism.", "She had to ___ the accusations with evidence.", ["Accept", "Agree", "Concede"]),
    ("Countryside", "The rural land outside towns and cities.", "They drove through the beautiful ___ to the coast.", ["City", "Urban", "Metropolis"]),
    ("Courage", "The ability to do something that frightens you.", "She showed great ___ in speaking out.", ["Cowardice", "Fear", "Timidity"]),
    ("Course", "The route or direction taken by something.", "The ___, not the destination, matters most.", ["Off-course", "Wrong", "Astray"]),
    ("Court", "A place where legal trials are held.", "The case will be heard in ___ next month.", ["Arbitration", "Mediation", "Settlement"]),
    ("Coziness", "The quality of being comfortable and warm.", "The ___ of the cabin made us want to stay forever.", ["Coldness", "Bareness", "Uncomfortableness"]),
    ("Craft", "To make something skillfully by hand.", "She learned to ___ beautiful pottery.", ["Destroy", "Break", "Demolish"]),
    ("Crash", "A violent collision, especially of vehicles.", "The car ___ was caused by icy roads.", ["Miss", "Avoid", "Dodge"]),
    ("Crawl", "To move slowly on hands and knees.", "The baby began to ___ across the floor.", ["Run", "Sprint", "Dash"]),
    ("Crazy", "Mentally deranged; very foolish.", "That idea sounds completely ___.", ["Sane", "Rational", "Sensible"]),
    ("Create", "To cause something to exist; to bring into being.", "Artists ___ beauty out of ordinary materials.", ["Destroy", "Demolish", "Annihilate"]),
    ("Credit", "The ability to obtain goods before payment.", "She used her ___ card to pay for the purchase.", ["Debt", "Defer", "Overdue"]),
    ("Crew", "A group of people working together.", "The ___ worked tirelessly to launch the ship.", ["Individual", "Solo", "Alone"]),
    ("Crime", "An illegal act punishable by law.", "He committed a ___ and had to face the consequences.", ["Virtue", "Good deed", "Morality"]),
    ("Crisis", "A time of intense difficulty or danger.", "The country faced an economic ___.", ["Stability", "Calm", "Peace"]),
    ("Crisp", "Firm, dry, and fresh; easily broken.", "The ___ autumn air smelled of fallen leaves.", ["Soggy", "Soft", "Limp"]),
    ("Critical", "Expressing adverse or disapproving comments.", "The review was ___ of the restaurant's service.", ["Complementary", "Praising", "Approving"]),
    ("Crop", "A cultivated plant harvested for food.", "The farmer's ___ failed due to drought.", ["Weed", "Wild", "Natural"]),
    ("Cross", "To go from one side to the other.", "Be careful when you ___ the street.", ["Stay", "Remain", "Wait"]),
    ("Crowd", "A large number of people gathered together.", "The ___ cheered at the concert.", ["Empty", "Deserted", "Sparse"]),
    ("Crucial", "Decisive or critical in determining the outcome.", "This evidence is ___ to the case.", ["Unimportant", "Trivial", "Minor"]),
    ("Cruel", "Willfully causing pain or suffering to others.", "The ___ treatment of animals is unacceptable.", ["Kind", "Gentle", "Compassionate"]),
    ("Crush", "To press or squeeze with force.", "The machine will ___ the cans for recycling.", ["Build", "Construct", "Create"]),
    ("Cry", "To shed tears as an expression of distress.", "It is okay to ___ when you feel sad.", ["Laugh", "Smile", "Rejoice"]),
    ("Cunning", "Having or showing skill in achieving aims by deceit.", "The ___ fox outwitted the hunters.", ["Honest", "Naive", "Straightforward"]),
    ("Cure", "To relieve or eliminate a disease or problem.", "The medicine will ___ the infection.", ["Worsen", "Harm", "Aggravate"]),
    ("Curious", "Eager to learn or know something.", "The ___ child asked endless questions.", ["Indifferent", "Apathetic", "Uninterested"]),
    ("Current", "Belonging to the present time.", "The ___ situation requires immediate attention.", ["Past", "Old", "Outdated"]),
    ("Curse", "A wish of harm or evil upon someone.", "The witch cast a ___ on the prince.", ["Blessing", "Gift", "Favor"]),
    ("Curve", "A line that bends gradually.", "The road ahead had a sharp ___.", ["Straight", "Linear", "Direct"]),
    ("Custom", "A traditional way of behaving.", "It is a ___ to exchange gifts during the holidays.", ["Innovation", "Modernity", "Novelty"]),
    ("Cycle", "A repeated sequence of events.", "The ___ of the seasons never ends.", ["One-time", "Unique", "Singular"])
]
