# Deck 1: General Knowledge (advanced SAT/GRE-level words)
WORDS_DECK_1 = [
    ("Ephemeral", "Lasting for a very short time; fleeting.", "The beauty of the sunset was ___, gone within minutes.", ["Permanent", "Eternal", "Everlasting"]),
    ("Ubiquitous", "Present or appearing everywhere.", "Smartphones have become ___ in modern society.", ["Rare", "Scarce", "Absent"]),
    ("Magnanimous", "Very generous or forgiving, especially toward a rival.", "The winner was ___ in victory, praising the opponent.", ["Petty", "Vindictive", "Spiteful"]),
    ("Perfidious", "Deceitful and untrustworthy; treacherous.", "The ___ ally betrayed the kingdom at the worst moment.", ["Loyal", "Faithful", "Honest"]),
    ("Obfuscate", "To render obscure, unclear, or unintelligible.", "Politicians often ___ the truth with complex language.", ["Clarify", "Illuminate", "Explain"]),
    ("Cacophony", "A harsh, discordant mixture of sounds.", "The ___ of car horns made sleep impossible.", ["Harmony", "Melody", "Silence"]),
    ("Serendipity", "The occurrence of events by chance in a happy way.", "Finding that book was pure ___.", ["Misfortune", "Calculation", "Intent"]),
    ("Sonder", "The realization that each passerby has a life as vivid as your own.", "Walking through the city, he was overcome with ___.", ["Apathy", "Indifference", "Narcissism"]),
    ("Eloquent", "Fluent or persuasive in speaking or writing.", "Her ___ speech moved the entire audience to tears.", ["Inarticulate", "Mumbled", "Hesitant"]),
    ("Pragmatic", "Dealing with things sensibly and realistically.", "We need a ___ solution, not an idealistic one.", ["Idealistic", "Impractical", "Fanciful"]),
    ("Resilient", "Able to withstand or recover quickly from difficult conditions.", "The ___ community rebuilt after the disaster.", ["Fragile", "Weak", "Delicate"]),
    ("Ambiguous", "Open to more than one interpretation; unclear.", "His ___ answer left everyone confused.", ["Clear", "Definite", "Explicit"]),
    ("Candid", "Truthful and straightforward; frank.", "She gave a ___ opinion about the proposal.", ["Deceptive", "Evasive", "Dishonest"]),
    ("Diligent", "Having or showing care in one's work or duties.", "The ___ student finished all assignments early.", ["Lazy", "Negligent", "Careless"]),
    ("Empathy", "The ability to understand and share the feelings of another.", "A good leader shows ___ toward their team.", ["Apathy", "Coldness", "Indifference"]),
    ("Frugal", "Sparing or economical with regard to money or food.", "Her ___ habits allowed her to save a fortune.", ["Wasteful", "Extravagant", "Lavish"]),
    ("Hypothetical", "Based on assumed conditions; not necessarily real.", "Let us consider a ___ scenario for discussion.", ["Actual", "Real", "Confirmed"]),
    ("Inevitable", "Certain to happen; unavoidable.", "Change is the only ___ thing in life.", ["Avoidable", "Preventable", "Unlikely"]),
    ("Judicious", "Having, showing, or done with good judgment.", "A ___ investment requires careful research.", ["Foolish", "Reckless", "Hasty"]),
    ("Lethargic", "Affected by lethargy; sluggish and apathetic.", "The heat made everyone feel ___ and unmotivated.", ["Energetic", "Vibrant", "Lively"]),
    ("Meticulous", "Showing great attention to detail; very careful.", "The ___ artisan inspected every stitch.", ["Careless", "Sloppy", "Negligent"]),
    ("Nostalgia", "A sentimental longing for the past.", "The old song filled her with ___ for childhood.", ["Aversion", "Disgust", "Indifference"]),
    ("Obsolete", "No longer produced or used; out of date.", "Flip phones are now considered ___.", ["Modern", "Current", "Contemporary"]),
    ("Placate", "To make someone less angry or hostile.", "He tried to ___ the upset customer with a refund.", ["Provoke", "Enrage", "Agitate"]),
    ("Quintessential", "Representing the most perfect example of a quality.", "Paris is the ___ romantic city.", ["Atypical", "Imperfect", "Unusual"]),
    ("Succinct", "Briefly and clearly expressed; concise.", "Her ___ summary captured all key points.", ["Verbose", "Wordy", "Lengthy"]),
    ("Tenacious", "Tending to keep a firm hold of something; persistent.", "The ___ reporter refused to drop the story.", ["Weak", "Yielding", "Surrendering"]),
    ("Unprecedented", "Never done or known before.", "The pandemic caused ___ global disruption.", ["Common", "Ordinary", "Typical"]),
    ("Versatile", "Able to adapt or be adapted to many functions.", "She is a ___ musician who plays six instruments.", ["Limited", "Inflexible", "Narrow"]),
    ("Wary", "Feeling or showing caution about possible dangers.", "Investors are ___ of the volatile market.", ["Trusting", "Careless", "Reckless"]),
    ("Zealous", "Having great energy or enthusiasm for a cause.", "The ___ activist campaigned tirelessly.", ["Apathetic", "Indifferent", "Half-hearted"]),
    ("Acerbic", "Sharp and forthright in tone; harsh or bitter.", "Her ___ wit often offended those she mocked.", ["Mild", "Sweet", "Gentle"]),
    ("Benevolent", "Well-meaning and kindly.", "The ___ donor funded the entire hospital wing.", ["Malevolent", "Cruel", "Selfish"]),
    ("Capricious", "Given to sudden changes of mood or behavior.", "The ___ weather shifted from sun to hail.", ["Consistent", "Stable", "Predictable"]),
    ("Deference", "Humble submission and respect.", "In ___ to tradition, they followed the old ritual.", ["Defiance", "Disrespect", "Rebellion"]),
    ("Ebullient", "Cheerful and full of energy.", "The ___ child brightened every room.", ["Gloomy", "Sullen", "Morose"]),
    ("Facetious", "Treating serious issues with inappropriate humor.", "His ___ remarks during the funeral were offensive.", ["Serious", "Solemn", "Grave"]),
    ("Gregarious", "Fond of company; sociable.", "Her ___ nature made her the life of every party.", ["Introverted", "Reserved", "Shy"]),
    ("Haughty", "Arrogantly superior and disdainful.", "The ___ celebrity ignored her fans.", ["Humble", "Modest", "Meek"]),
    ("Impetuous", "Acting or done quickly without thought.", "His ___ decision to quit cost him dearly.", ["Cautious", "Deliberate", "Thoughtful"]),
    ("Lucid", "Expressed clearly; easy to understand.", "The professor gave a ___ explanation of quantum theory.", ["Confusing", "Obscure", "Vague"]),
    ("Morose", "Sullen and ill-tempered; gloomy.", "After the loss, he was ___ for weeks.", ["Cheerful", "Jovial", "Optimistic"]),
    ("Nefarious", "Wicked or criminal.", "The ___ plot was foiled by the authorities.", ["Virtuous", "Righteous", "Honorable"]),
    ("Opulent", "Ostentatiously rich and luxurious; lavish.", "The ___ palace was adorned with gold leaf.", ["Sparse", "Frugal", "Austere"]),
    ("Sagacious", "Having keen mental discernment and good judgment.", "The ___ elder advised the young chief wisely.", ["Foolish", "Ignorant", "Obstinate"]),
    ("Taciturn", "Reserved or uncommunicative in speech; saying little.", "The ___ cowboy spoke only when necessary.", ["Talkative", "Garrulous", "Loquacious"]),
    ("Venerable", "Accorded great respect due to age or wisdom.", "The ___ cathedral had stood for centuries.", ["Disrespected", "Ignored", "Neglected"]),
    ("Ameliorate", "To make something bad or unsatisfactory better.", "New policies aim to ___ living conditions.", ["Worsen", "Aggravate", "Exacerbate"]),
    ("Bellicose", "Demonstrating aggression and willingness to fight.", "The ___ general wanted war at any cost.", ["Peaceful", "Pacifist", "Diplomatic"]),
    ("Cogent", "Clear, logical, and convincing.", "Her ___ argument swayed the jury.", ["Weak", "Illogical", "Unconvincing"]),
    ("Enervate", "To cause someone to feel drained of energy.", "The humid heat ___d the hikers.", ["Invigorate", "Energize", "Strengthen"]),
    ("Garrulous", "Excessively talkative, especially on trivial matters.", "The ___ passenger talked through the entire flight.", ["Taciturn", "Quiet", "Reserved"]),
    ("Hubris", "Excessive pride or self-confidence.", "His ___ led to his downfall.", ["Humility", "Modesty", "Meekness"]),
    ("Iconoclast", "A person who attacks cherished beliefs or institutions.", "The ___ artist challenged every artistic convention.", ["Traditionalist", "Conformist", "Follower"]),
    ("Juxtapose", "To place close together for contrasting effect.", "The film ___s wealth and poverty.", ["Separate", "Divide", "Isolate"]),
    ("Languid", "Displaying a lack of physical or mental energy.", "She moved with ___ grace in the summer heat.", ["Energetic", "Vibrant", "Lively"]),
    ("Malevolent", "Having or showing a wish to do evil to others.", "The villain's ___ laugh echoed through the hall.", ["Benevolent", "Kind", "Compassionate"]),
    ("Nascent", "Just beginning to develop; not fully formed.", "The ___ democracy faced many challenges.", ["Mature", "Developed", "Established"]),
    ("Ominous", "Giving the impression that something bad will happen.", "The ___ clouds signaled an approaching storm.", ["Promising", "Favorable", "Hopeful"]),
    ("Paradigm", "A typical example or pattern of something.", "This discovery shifted the scientific ___.", ["Anomaly", "Exception", "Deviation"]),
    ("Quixotic", "Exceedingly idealistic; unrealistic and impractical.", "His ___ quest for perfection doomed the project.", ["Realistic", "Pragmatic", "Practical"]),
    ("Recalcitrant", "Having an obstinately uncooperative attitude.", "The ___ student refused to follow instructions.", ["Compliant", "Obedient", "Cooperative"]),
    ("Trepidation", "A feeling of fear or agitation about something.", "She approached the exam with ___.", ["Confidence", "Boldness", "Fearlessness"]),
    ("Vociferous", "Loud and forceful in expression of feelings.", "The ___ protestors demanded justice.", ["Quiet", "Muted", "Silent"]),
    ("Aberration", "A departure from what is normal or expected.", "The warm winter was a statistical ___.", ["Norm", "Standard", "Regularity"]),
    ("Circumspect", "Wary and unwilling to take risks; cautious.", "Investors should be ___ in volatile markets.", ["Reckless", "Rash", "Impulsive"]),
    ("Debacle", "A sudden and ignominious failure; a fiasco.", "The product launch was a complete ___.", ["Success", "Triumph", "Victory"]),
    ("Exacerbate", "To make a problem or situation worse.", "His comments only ___d the conflict.", ["Alleviate", "Soothe", "Mitigate"]),
    ("Germane", "Relevant to a subject under consideration.", "That question is not ___ to the discussion.", ["Irrelevant", "Unrelated", "Tangential"]),
    ("Idyllic", "Extremely happy, peaceful, or picturesque.", "They lived an ___ life in the countryside.", ["Chaotic", "Stressful", "Miserable"]),
    ("Misnomer", "A wrong or inaccurate name or designation.", "Calling it a 'cottage' is a ___; it is a mansion.", ["Accuracy", "Truth", "Correctness"]),
    ("Nonchalant", "Feeling or appearing casually calm and relaxed.", "He was ___ about the impending deadline.", ["Anxious", "Worried", "Nervous"]),
    ("Ostensible", "Stated or appearing to be true but not necessarily so.", "His ___ reason for visiting was business.", ["Genuine", "Actual", "Real"]),
    ("Pedantic", "Excessively concerned with minor details or rules.", "The ___ professor corrected every pronunciation.", ["Careless", "Casual", "Sloppy"]),
    ("Quell", "To put an end to something; to suppress.", "The police were called to ___ the riot.", ["Provoke", "Incite", "Ignite"]),
    ("Reprehensible", "Deserving censure or condemnation.", "His ___ behavior angered everyone.", ["Admirable", "Praiseworthy", "Laudable"]),
    ("Sycophant", "A person who acts obsequiously to gain advantage.", "The ___ flattered the boss endlessly.", ["Rebel", "Critic", "Adversary"]),
    ("Tepid", "Only slightly warm; lukewarm; unenthusiastic.", "The audience gave a ___ response to the performance.", ["Passionate", "Enthusiastic", "Ardent"]),
    ("Unequivocal", "Leaving no doubt; unambiguous.", "The evidence was ___ in proving his guilt.", ["Ambiguous", "Vague", "Unclear"]),
    ("Acrimony", "Bitterness or ill feeling in speech or manner.", "The debate was marked by ___ and insults.", ["Harmony", "Civility", "Politeness"]),
    ("Conundrum", "A confusing and difficult problem or question.", "The ethical ___ puzzled the philosophers.", ["Solution", "Answer", "Resolution"]),
    ("Egregious", "Outstandingly bad; shocking.", "The error was ___ and cost the company millions.", ["Minor", "Slight", "Trivial"]),
    ("Fortuitous", "Happening by accident or chance; lucky.", "Their meeting was entirely ___.", ["Planned", "Intentional", "Deliberate"]),
    ("Indolent", "Wanting to avoid exertion; lazy.", "The ___ cat slept all day in the sun.", ["Energetic", "Industrious", "Active"]),
    ("Laconic", "Using very few words; brief and concise.", "His ___ reply was simply 'No.'", ["Verbose", "Garrulous", "Wordy"]),
    ("Mercurial", "Subject to sudden or unpredictable changes.", "His ___ temperament made him hard to work with.", ["Stable", "Consistent", "Steady"]),
    ("Obsequious", "Obedient or attentive to an excessive degree.", "The ___ waiter hovered constantly.", ["Assertive", "Defiant", "Bold"]),
    ("Reticent", "Not revealing thoughts or feelings readily.", "She was ___ about her personal life.", ["Frank", "Open", "Candid"]),
    ("Sanguine", "Optimistic or positive, especially in a difficult situation.", "Despite the losses, she remained ___.", ["Pessimistic", "Gloomy", "Hopeless"]),
    ("Transient", "Lasting only for a short time; impermanent.", "The ___ beauty of cherry blossoms is cherished.", ["Permanent", "Enduring", "Eternal"]),
    ("Acumen", "The ability to make good judgments and decisions.", "Her business ___ made her a millionaire.", ["Stupidity", "Ignorance", "Ineptitude"]),
    ("Benign", "Gentle and kindly; not harmful.", "The tumor was ___ and required no treatment.", ["Malignant", "Harmful", "Deadly"]),
    ("Complacent", "Showing smug or uncritical satisfaction with oneself.", "The ___ manager ignored the warning signs.", ["Ambitious", "Driven", "Concerned"]),
    ("Demagogue", "A political leader who appeals to popular desires.", "The ___ manipulated public fear for power.", ["Diplomat", "Statesman", "Humanitarian"]),
    ("Fervent", "Having or displaying a passionate intensity.", "The ___ supporters cheered for hours.", ["Apathetic", "Indifferent", "Half-hearted"]),
    ("Hackneyed", "Lacking significance through overuse; clichéd.", "The plot was ___ and utterly predictable.", ["Original", "Fresh", "Novel"]),
    ("Imperious", "Assuming power or authority without justification.", "The ___ manager demanded immediate compliance.", ["Humble", "Submissive", "Meek"]),
    ("Jovial", "Cheerful and friendly.", "The ___ host made everyone feel welcome.", ["Sullen", "Gloomy", "Morose"]),
    ("Lugubrious", "Looking or sounding sad and dismal.", "The ___ music matched the funereal atmosphere.", ["Cheerful", "Joyful", "Lively"]),
    ("Mundane", "Lacking interest or excitement; dull.", "She longed to escape her ___ routine.", ["Exciting", "Extraordinary", "Fascinating"]),
    ("Ostentatious", "Designed to impress or attract notice.", "The ___ display of wealth was vulgar.", ["Modest", "Humble", "Understated"]),
    ("Prodigal", "Spending money freely; wasteful.", "The ___ heir squandered the entire fortune.", ["Frugal", "Thrifty", "Economical"]),
    ("Solicitous", "Characterized by showing interest or concern.", "The ___ nurse cared for every patient tenderly.", ["Indifferent", "Negligent", "Uncaring"]),
    ("Usurp", "To seize power or position illegally.", "The general tried to ___ the throne.", ["Earn", "Merit", "Deserve"]),
    ("Volatile", "Liable to change rapidly and unpredictably.", "The ___ political climate worried investors.", ["Stable", "Steady", "Calm"]),
    ("Affable", "Friendly, good-natured, and easy to talk to.", "The ___ host greeted everyone with a warm smile.", ["Grumpy", "Rude", "Hostile"]),
    ("Banal", "So lacking in originality as to be obvious and boring.", "The movie's dialogue was ___ and uninspired.", ["Original", "Fresh", "Innovative"]),
    ("Dearth", "A scarcity or lack of something.", "There is a ___ of affordable housing.", ["Abundance", "Plenty", "Surplus"]),
    ("Futile", "Incapable of producing any useful result; pointless.", "All attempts to save the company were ___.", ["Effective", "Useful", "Productive"]),
    ("Grandiose", "Impressive or magnificent in appearance or style.", "The ___ mansion dominated the hilltop.", ["Modest", "Humble", "Plain"]),
    ("Incendiary", "Tending to stir up conflict; inflammatory.", "The politician's ___ remarks sparked outrage.", ["Pacifying", "Soothing", "Conciliatory"]),
    ("Lethargy", "A lack of energy and enthusiasm.", "The heat induced a state of ___.", ["Vigor", "Energy", "Vitality"]),
    ("Nebulous", "In the form of a cloud or haze; vague.", "His plans were still ___ and undefined.", ["Clear", "Definite", "Concrete"]),
    ("Penchant", "A strong or habitual liking for something.", "She has a ___ for expensive jewelry.", ["Dislike", "Aversion", "Abhorrence"]),
    ("Repudiate", "To refuse to accept or be associated with.", "The leader ___d all forms of violence.", ["Embrace", "Accept", "Adopt"]),
    ("Scrupulous", "Diligent and thorough; conscientious.", "The ___ accountant checked every figure.", ["Careless", "Negligent", "Sloppy"]),
    ("Terse", "Sparing in the use of words; abrupt.", "His ___ note read simply 'Come home.'", ["Verbose", "Wordy", "Lengthy"]),
    ("Vacillate", "To alternate or waver between opinions.", "She ___d between the two job offers.", ["Decide", "Commit", "Resolve"]),
    ("Wistful", "Full of yearning or melancholy longing.", "She cast a ___ glance at the old photographs.", ["Content", "Satisfied", "Cheerful"]),
    ("Auspicious", "Conducive to success; favorable.", "The clear sky was an ___ sign for the launch.", ["Ominous", "Unfavorable", "Inauspicious"]),
    ("Dogmatic", "Inclined to assert principles as undeniably true.", "The ___ preacher accepted no dissent.", ["Open-minded", "Flexible", "Tolerant"]),
    ("Eclectic", "Deriving ideas from a broad range of sources.", "His ___ taste ranged from jazz to opera.", ["Narrow", "Limited", "Restricted"]),
    ("Hierarchy", "A system in which members are ranked by status.", "The corporate ___ was rigidly enforced.", ["Equality", "Egalitarianism", "Anarchy"]),
    ("Impartial", "Treating all rivals or disputants equally; fair.", "A judge must remain ___ at all times.", ["Biased", "Partial", "Prejudiced"]),
    ("Laudable", "Deserving praise and commendation.", "The charity's work is ___.", ["Blameworthy", "Deplorable", "Despicable"]),
    ("Malleable", "Easily influenced or shaped.", "Young minds are highly ___.", ["Rigid", "Stubborn", "Inflexible"]),
    ("Nuance", "A subtle difference in meaning or expression.", "The actor brought ___ to the complex role.", ["Bluntness", "Simplicity", "Obviousness"]),
    ("Opaque", "Not able to be seen through; not transparent.", "The motives behind the decision remain ___.", ["Clear", "Transparent", "Obvious"]),
    ("Paradox", "A seemingly contradictory but possibly true statement.", "It is a ___ that solitude can feel crowded.", ["Consistency", "Agreement", "Certainty"]),
    ("Spurious", "Not being what it purports to be; false.", "The ___ claim was debunked by experts.", ["Genuine", "Authentic", "Valid"]),
    ("Tangential", "Diverging from a previous course; peripheral.", "His question was ___ to the main topic.", ["Central", "Relevant", "Direct"]),
    ("Utilitarian", "Designed to be useful rather than attractive.", "The furniture was purely ___.", ["Ornate", "Decorative", "Luxurious"]),
    ("Alacrity", "Brisk and cheerful readiness.", "She accepted the challenge with ___.", ["Reluctance", "Apathy", "Indifference"]),
    ("Conjecture", "An opinion formed on incomplete information.", "The theory is pure ___ without evidence.", ["Fact", "Proof", "Certainty"]),
    ("Disparity", "A great difference between things.", "The wealth ___ in the city was glaring.", ["Equality", "Similarity", "Parity"]),
    ("Furtive", "Attempting to avoid notice or attention.", "He cast a ___ glance at the document.", ["Open", "Overt", "Honest"]),
    ("Harbinger", "A person or thing that announces the approach of another.", "The robin is a ___ of spring.", ["Follower", "Result", "Aftermath"]),
    ("Immutable", "Unchanging over time; unalterable.", "The laws of physics are not ___.", ["Changeable", "Flexible", "Variable"]),
    ("Mitigate", "To make less severe or serious.", "Measures were taken to ___ the damage.", ["Aggravate", "Worsen", "Intensify"]),
    ("Ravenous", "Extremely hungry; voracious.", "After the hike, they were ___.", ["Sated", "Full", "Satisfied"]),
    ("Stagnant", "Showing no activity; dull and sluggish.", "The economy remained ___ for years.", ["Dynamic", "Active", "Growing"]),
    ("Tumultuous", "Making a loud, confused noise; uproarious.", "The ___ crowd stormed the gates.", ["Calm", "Peaceful", "Orderly"]),
    ("Vapid", "Offering nothing stimulating or challenging; bland.", "The conversation was ___ and boring.", ["Engaging", "Stimulating", "Lively"]),
    ("Deleterious", "Causing harm or damage.", "The chemical has ___ effects on health.", ["Beneficial", "Helpful", "Salutary"]),
    ("Enigma", "A person or thing that is mysterious or puzzling.", "The old mansion remained an ___.", ["Open", "Clear", "Obvious"]),
    ("Hypocrite", "A person who pretends to have higher standards.", "He was exposed as a ___.", ["Sincere", "Honest", "Genuine"]),
    ("Onerous", "Involving a great deal of effort; burdensome.", "The ___ task exhausted the team.", ["Easy", "Light", "Simple"]),
    ("Stoic", "A person who endures hardship without complaint.", "He remained ___ despite the pain.", ["Emotional", "Sensitive", "Dramatic"]),
    ("Tenable", "Able to be maintained or defended.", "The theory is no longer ___ given the evidence.", ["Unreasonable", "Indefensible", "Weak"]),
    ("Verbose", "Using more words than needed; wordy.", "The ___ report could have been a single page.", ["Concise", "Succinct", "Brief"]),
    ("Clandestine", "Kept secret or done secretively.", "The ___ meeting was held in a basement.", ["Open", "Public", "Overt"]),
    ("Eradicate", "To destroy completely; to put an end to.", "The goal is to ___ the disease entirely.", ["Preserve", "Protect", "Cultivate"]),
    ("Fallacy", "A mistaken belief based on unsound reasoning.", "It is a ___ to assume wealth equals happiness.", ["Truth", "Fact", "Reality"]),
    ("Heresy", "Belief or opinion contrary to orthodox doctrine.", "His views were condemned as ___.", ["Orthodoxy", "Dogma", "Convention"]),
    ("Astute", "Having an ability to accurately assess situations.", "The ___ investor foresaw the market crash.", ["Foolish", "Naive", "Oblivious"]),
    ("Divulge", "To make known something private or secret.", "The spy refused to ___ classified information.", ["Conceal", "Hide", "Suppress"]),
    ("Extravagant", "Lacking restraint in spending money; excessive.", "The ___ wedding cost a fortune.", ["Frugal", "Thrifty", "Modest"]),
    ("Gullible", "Easily persuaded to believe something; credulous.", "The ___ tourist fell for every scam.", ["Skeptical", "Cynical", "Distrustful"]),
    ("Maverick", "An unorthodox or independent-minded person.", "The ___ politician refused to follow party lines.", ["Conformist", "Follower", "Traditionalist"]),
    ("Capitulate", "To cease to resist an opponent; to surrender.", "The fortress finally ___d after a long siege.", ["Resist", "Defy", "Fight"]),
    ("Disdain", "The feeling that something is beneath one.", "She looked at the mess with ___.", ["Admiration", "Respect", "Approval"]),
    ("Empirical", "Based on observation or experience.", "The theory requires ___ evidence.", ["Theoretical", "Speculative", "Hypothetical"]),
    ("Modicum", "A small quantity of someone.", "Anyone with a ___ of sense would agree.", ["Abundance", "Plenty", "Surplus"]),
    ("Perpetual", "Never ending or changing; continuous.", "The city is in a state of ___ motion.", ["Temporary", "Brief", "Momentary"]),
    ("Virtuoso", "A person highly skilled in music or another art.", "The ___ pianist captivated the audience.", ["Amateur", "Novice", "Beginner"]),
    ("Coerce", "To persuade by force or threats.", "The confession was ___d through torture.", ["Encourage", "Persuade", "Convince"]),
    ("Fabricate", "To invent something falsely.", "The witness ___d the entire story.", ["Reveal", "Disclose", "Expose"]),
    ("Imminent", "About to happen; impending.", "The storm was ___, so they took shelter.", ["Distant", "Remote", "Unlikely"]),
    ("Lament", "To express sorrow or regret.", "They ___ed the loss of their friend.", ["Celebrate", "Rejoice", "Exult"]),
    ("Staunch", "Loyal and committed in attitude.", "She remained a ___ supporter of the cause.", ["Disloyal", "Unfaithful", "Fickle"]),
    ("Uncanny", "Strange or mysterious; unsettling.", "He had an ___ ability to predict outcomes.", ["Normal", "Ordinary", "Natural"]),
    ("Zealot", "A person who is fanatical and uncompromising.", "The religious ___ would not tolerate dissent.", ["Moderate", "Tolerant", "Liberal"]),
    ("Censure", "To express severe disapproval of someone.", "The senator was ___d for misconduct.", ["Praise", "Approve", "Commend"]),
    ("Disingenuous", "Not candid or sincere;假装坦诚.", "His ___ apology fooled no one.", ["Sincere", "Honest", "Candid"]),
    ("Epitome", "A person or thing that is a perfect example.", "She was the ___ of grace and elegance.", ["Opposite", "Antithesis", "Contrary"]),
    ("Impasse", "A situation with no progress; deadlock.", "The negotiations reached an ___.", ["Breakthrough", "Progress", "Solution"]),
    ("Latent", "Existing but not yet developed or manifest.", "Her ___ talent was discovered later in life.", ["Obvious", "Active", "Evident"]),
    ("Nepotism", "Favoritism shown to relatives in business.", "The company was rife with ___.", ["Meritocracy", "Fairness", "Impartiality"]),
    ("Pertinent", "Relevant or applicable to a matter.", "The evidence was ___ to the case.", ["Irrelevant", "Unrelated", "Inapplicable"]),
    ("Succumb", "To fail to resist pressure or an attack.", "He finally ___ed to the illness.", ["Resist", "Withstand", "Survive"]),
    ("Vilify", "To speak or write about in an abusively disparaging manner.", "The media ___d the politician mercilessly.", ["Praise", "Commend", "Extol"]),
    ("Abstain", "To restrain oneself from doing something.", "She decided to ___ from alcohol.", ["Indulge", "Partake", "Participate"]),
    ("Blasphemy", "Profane speaking about God or sacred things.", "His comments were considered ___ by the church.", ["Reverence", "Piety", "Devotion"]),
    ("Compliant", "Inclined to agree with others; obedient.", "The ___ employee never questioned orders.", ["Defiant", "Rebellious", "Disobedient"]),
    ("Indifferent", "Having no particular interest or concern.", "He was ___ to the outcome of the vote.", ["Concerned", "Invested", "Interested"]),
    ("Legitimate", "Conforming to the law or to rules.", "The business was entirely ___.", ["Illegal", "Fraudulent", "Illegitimate"]),
    ("Novice", "A person new to a field or activity.", "The ___ chef burned the meal.", ["Expert", "Veteran", "Master"]),
    ("Prolific", "Producing much fruit or many works.", "The ___ author wrote fifty novels.", ["Unproductive", "Infertile", "Barren"]),
    ("Rampant", "Flourishing or spreading unchecked.", "Corruption was ___ in the regime.", ["Controlled", "Checked", "Limited"]),
    ("Skeptical", "Not easily convinced; having doubts.", "She was ___ of his promises.", ["Trusting", "Gullible", "Naive"]),
    ("Virulent", "Extremely severe or harmful in effects.", "The ___ strain of flu spread rapidly.", ["Mild", "Harmless", "Benign"]),
    ("Depreciate", "To diminish in value over time.", "Cars ___ rapidly after purchase.", ["Appreciate", "Increase", "Rise"]),
    ("Empower", "To give someone the authority or power.", "Education ___s individuals to improve their lives.", ["Disempower", "Suppress", "Subjugate"]),
    ("Antagonize", "To cause someone to become hostile.", "His rude remarks ___d the entire room.", ["Appease", "Soothe", "Pacify"]),
    ("Bombastic", "High-sounding but with little meaning; inflated.", "The speech was ___ but said nothing.", ["Humble", "Understated", "Modest"]),
    ("Elucidate", "To make something clear; to explain.", "The professor ___d the complex theory.", ["Confuse", "Obfuscate", "Muddle"]),
    ("Fortitude", "Courage in pain or adversity.", "She faced the illness with remarkable ___.", ["Cowardice", "Weakness", "Timidity"]),
    ("Magnate", "A wealthy and influential person in business.", "The oil ___ owned vast refineries.", ["Pauper", "Beggar", "Nobody"]),
    ("Propitious", "Indicating a good chance of success; favorable.", "The ___ weather made for a perfect wedding.", ["Unfavorable", "Inauspicious", "Ominous"]),
    ("Resilience", "The capacity to recover quickly from difficulties.", "Her ___ allowed her to bounce back from failure.", ["Weakness", "Fragility", "Vulnerability"]),
    ("Unassuming", "Not pretentious or arrogant; modest.", "The ___ celebrity lived like an ordinary person.", ["Arrogant", "Pretentious", "Showy"]),
    ("Anomaly", "Something that deviates from the norm.", "The warm winter was a climatic ___.", ["Norm", "Standard", "Regularity"]),
    ("Empirical", "Based on observation or experience rather than theory.", "The study provides ___ data supporting the hypothesis.", ["Theoretical", "Speculative", "Abstract"]),
    ("Hypothesize", "To put forward as a hypothesis.", "Scientists ___ that life exists on other planets.", ["Prove", "Confirm", "Validate"]),
    ("Integrity", "The quality of being honest and moral.", "His ___ was never questioned.", ["Corruption", "Dishonesty", "Deceit"]),
    ("Nostalgic", "Longing for the past.", "The old film made her feel ___.", ["Indifferent", "Content", "Forward-looking"]),
    ("Remnant", "A small remaining quantity of something.", "The ___s of the meal were thrown away.", ["Whole", "Entirety", "Bulk"]),
    ("Stagnate", "To become inactive or cease developing.", "Without innovation, the company will ___.", ["Grow", "Thrive", "Progress"]),
    ("Abhor", "To regard with disgust and hatred.", "She ___s any form of cruelty.", ["Love", "Adore", "Cherish"]),
    ("Gesticulate", "To use gestures to emphasize one's words.", "He ___d wildly while telling the story.", ["Still", "Mute", "Calm"]),
    ("Rescind", "To revoke or cancel officially.", "The contract was ___ed due to breach.", ["Enforce", "Uphold", "Maintain"]),
    ("Unwarranted", "Not justified or authorized.", "The criticism was harsh and ___.", ["Justified", "Warranted", "Deserved"]),
    ("Pensive", "Engaged in deep or serious thought.", "She grew ___ while staring at the old photograph.", ["Frivolous", "Shallow", "Vacant"]),
    ("Rancor", "Bitterness or resentfulness, especially when long-standing.", "She held no ___ after the divorce.", ["Goodwill", "Kindness", "Forgiveness"]),
    ("Umbrage", "Offense or annoyance; shade or shadow.", "He took ___ at the slightest criticism.", ["Pleasure", "Delight", "Satisfaction"]),
    ("Whimsical", "Playfully quaint or fanciful; unpredictable.", "The ___ garden featured winding paths and hidden statues.", ["Serious", "Dull", "Monotonous"]),
    ("Didactic", "Intended to teach or instruct excessively.", "The novel was ___, sacrificing story for moral lessons.", ["Entertaining", "Subtle", "Artistic"]),
    ("Frivolous", "Not having any serious purpose or value.", "The lawsuit was dismissed as ___.", ["Serious", "Important", "Meaningful"]),
    ("Sardonic", "Grimly mocking or cynical.", "His ___ humor masked deep sadness.", ["Sincere", "Warm", "Earnest"]),
    ("Vindicate", "To clear someone of blame or suspicion.", "The new evidence ___d the accused.", ["Convict", "Accuse", "Blame"]),
    ("Dissipate", "To disperse or scatter; to vanish.", "The fog ___d as the sun rose.", ["Gather", "Concentrate", "Collect"]),
    ("Perfunctory", "Carried out with minimal effort; cursory.", "He gave the report a ___ glance.", ["Thorough", "Meticulous", "Careful"]),
    ("Vicarious", "Experienced through the feelings of another.", "He felt ___ pride watching his son graduate.", ["Direct", "Personal", "Firsthand"]),
    ("Euphemism", "A mild expression substituted for a harsh one.", "'Passed away' is a ___ for 'died.'", ["Bluntness", "Directness", "Honesty"]),
    ("Nihilism", "The rejection of all religious and moral principles.", "His ___ left him without purpose or hope.", ["Faith", "Optimism", "Idealism"]),
    ("Quandary", "A state of perplexity or uncertainty.", "She was in a ___ about which offer to accept.", ["Certainty", "Clarity", "Solution"]),
    ("Tantamount", "Equivalent in seriousness to; virtually the same as.", "His silence was ___ to an admission of guilt.", ["Different", "Opposite", "Unrelated"]),
    ("Equivocal", "Open to more than one interpretation; ambiguous.", "Her ___ statement satisfied no one.", ["Clear", "Definite", "Unambiguous"]),
    ("Harangue", "A lengthy and aggressive speech or lecture.", "The boss delivered a ___ about productivity.", ["Compliment", "Praise", "Whisper"]),
    ("Penurious", "Extremely poor; poverty-stricken.", "The ___ family lived in a shack.", ["Wealthy", "Affluent", "Prosperous"]),
    ("Aberrant", "Departing from the normal or usual course.", "His ___ behavior alarmed his family.", ["Normal", "Typical", "Conventional"]),
    ("Concede", "To admit that something is true after resisting.", "He had to ___ that he was wrong.", ["Deny", "Contest", "Refute"]),
    ("Dormant", "Having normal functions suspended; inactive.", "The volcano had been ___ for centuries.", ["Active", "Erupting", "Awake"]),
    ("Extol", "To praise enthusiastically.", "The article ___led the virtues of organic farming.", ["Criticize", "Denounce", "Censure"]),
    ("Garish", "Obtrusively bright and showy; lurid.", "The ___ neon sign hurt their eyes.", ["Subtle", "Muted", "Elegant"]),
    ("Incognito", "With one's true identity concealed.", "The celebrity traveled ___ to avoid fans.", ["Openly", "Publicly", "Known"]),
    ("Truncate", "To shorten by cutting off the top or end.", "The article was ___d to fit the page.", ["Extend", "Lengthen", "Elongate"]),
    ("Catharsis", "The process of releasing strong emotions.", "Crying provided emotional ___.", ["Suppression", "Repression", "Control"]),
    ("Jaunty", "Having a lively, cheerful, and self-confident manner.", "He walked with a ___ step despite the bad news.", ["Dreary", "Dismal", "Somber"]),
    ("Patronize", "To treat with apparent kindness that betrays superiority.", "He ___d the staff with condescending praise.", ["Respect", "Honor", "Admire"]),
    ("Rudimentary", "Involving basic principles; elementary.", "He had only a ___ understanding of physics.", ["Advanced", "Complex", "Sophisticated"]),
    ("Dogged", "Having persistent determination.", "The ___ detective refused to give up.", ["Half-hearted", "Apathetic", "Lazy"]),
    ("Turbulent", "Characterized by conflict or disorder.", "The ___ era was marked by wars and upheaval.", ["Peaceful", "Calm", "Serene"]),
    ("Predicament", "A difficult or unpleasant situation.", "She found herself in a financial ___.", ["Solution", "Escape", "Advantage"]),
]

# Deck 2: Academic
WORDS_DECK_2 = [
    ("Hegemony", "Leadership or dominance by one group over others, especially in politics.", "The superpower maintained regional ___ through economic influence.", ["Subjugation", "Equality", "Autonomy"]),
    ("Ontology", "The branch of metaphysics dealing with the nature of being.", "The philosopher's ___ distinguished between physical and abstract entities.", ["Epistemology", "Theology", "Ethics"]),
    ("Epistemology", "The theory of knowledge, especially regarding its methods and validity.", "___ asks how we can truly know anything at all.", ["Metaphysics", "Logic", "Semantics"]),
    ("Heuristic", "A practical method not guaranteed to be optimal but sufficient.", "The ___ approach solved the problem quickly, albeit imperfectly.", ["Algorithmic", "Exact", "Precise"]),
    ("Pedagogy", "The method and practice of teaching.", "Modern ___ emphasizes student-centered learning.", ["Andragogy", "Demagoguery", "Propaganda"]),
    ("Dialectic", "The art of investigating truth through discussion.", "The Socratic ___ involves a systematic exchange of questions.", ["Monologue", "Rhetoric", "Dogma"]),
    ("Teleology", "The explanation of phenomena by their purpose rather than cause.", "___ argues that everything has an ultimate goal or design.", ["Causality", "Mechanism", "Randomness"]),
    ("Syllogism", "A logical argument using deductive reasoning.", "A classic ___: all men are mortal; Socrates is a man; therefore...", ["Paradox", "Fallacy", "Aphorism"]),
    ("Empiricism", "The theory that knowledge comes from sensory experience.", "___ rejects innate ideas in favor of observation.", ["Rationalism", "Idealism", "Skepticism"]),
    ("Rationalism", "The belief that reason is the chief source of knowledge.", "Descartes' ___ led him to 'I think, therefore I am.'", ["Empiricism", "Mysticism", "Fatalism"]),
    ("Determinism", "The doctrine that all events are determined by prior causes.", "___ suggests free will is an illusion.", ["Libertarianism", "Indeterminism", "Free will"]),
    ("Utilitarianism", "The ethical theory that maximizes happiness for the most people.", "___ judges actions by their consequences on well-being.", ["Deontology", "Hedonism", "Stoicism"]),
    ("Deontology", "An ethical theory based on duties and rules.", "Kantian ___ holds that lying is always wrong.", ["Utilitarianism", "Consequentialism", "Relativism"]),
    ("Solipsism", "The view that the self is all that can be known to exist.", "___ leads to the conclusion that external reality may be an illusion.", ["Realism", "Materialism", "Dualism"]),
    ("Phenomenology", "The study of structures of consciousness as experienced.", "___ investigates how things appear in our subjective experience.", ["Objectivism", "Behaviorism", "Reductionism"]),
    ("Structuralism", "A method analyzing phenomena through their underlying structures.", "___ in linguistics examines how language elements relate.", ["Post-structuralism", "Functionalism", "Formalism"]),
    ("Existentialism", "A philosophy emphasizing individual freedom and choice.", "___ asserts that existence precedes essence.", ["Essentialism", "Nihilism", "Stoicism"]),
    ("Metaphysics", "The branch of philosophy examining the nature of reality.", "___ addresses questions of being, time, and existence.", ["Physics", "Ethics", "Epistemology"]),
    ("Taxonomy", "The classification of things into ordered categories.", "Linnaean ___ organizes all living species hierarchically.", ["Typology", "Chronology", "Anatomy"]),
    ("Pragmatism", "An approach evaluating ideas by their practical consequences.", "American ___ influenced modern education and law.", ["Idealism", "Dogmatism", "Utopianism"]),
    ("Reductionism", "The practice of simplifying complex phenomena.", "___ in biology explains life purely by chemical reactions.", ["Holism", "Emergentism", "Complexity"]),
    ("Methodology", "A system of methods used in a particular field.", "The research ___ included both surveys and interviews.", ["Chaos", "Randomness", "Improvisation"]),
    ("Hypothesis", "A proposed explanation made on limited evidence.", "The ___ was tested through a controlled experiment.", ["Conclusion", "Fact", "Certainty"]),
    ("Synthesis", "The combination of ideas to form a coherent whole.", "The paper offers a ___ of existing research on climate change.", ["Analysis", "Fragmentation", "Division"]),
    ("Extrapolate", "To extend the application of findings beyond the known.", "We can ___ future trends from the current data.", ["Limit", "Restrict", "Confine"]),
    ("Corroborate", "To confirm or give support to a statement or theory.", "The witness testimony ___s the physical evidence.", ["Contradict", "Refute", "Disprove"]),
    ("Exegesis", "Critical explanation or interpretation of a text.", "The scholar's ___ of the poem revealed hidden meanings.", ["Paraphrase", "Summary", "Literal"]),
    ("Dichotomy", "A division into two mutually exclusive groups.", "The ___ between mind and body has long been debated.", ["Continuum", "Unity", "Agreement"]),
    ("Reciprocity", "The exchange of things with others for mutual benefit.", "The treaty was based on ___ between the two nations.", ["Exploitation", "Selfishness", "Competition"]),
    ("Holism", "The theory that systems should be viewed as wholes.", "___ opposes reductionism by emphasizing interconnectedness.", ["Reductionism", "Atomism", "Individualism"]),
    ("Amalgamate", "To combine or unite to form one structure.", "The two departments were ___d into a single unit.", ["Separate", "Divide", "Fragment"]),
    ("Cognizant", "Having knowledge or being aware of something.", "We must be ___ of the risks before proceeding.", ["Unaware", "Ignorant", "Oblivious"]),
    ("Disseminate", "To spread information or knowledge widely.", "The organization ___s health information to rural communities.", ["Conceal", "Suppress", "Withhold"]),
    ("Equanimity", "Mental calmness and composure, especially in stress.", "She faced the crisis with remarkable ___.", ["Anxiety", "Agitation", "Distress"]),
    ("Facilitate", "To make an action or process easier.", "The new software will ___ data analysis.", ["Hinder", "Impede", "Obstruct"]),
    ("Hierarchical", "Arranged in order of rank or importance.", "The ___ structure of the organization delayed decisions.", ["Egalitarian", "Flat", "Horizontal"]),
    ("Illuminate", "To light up or clarify intellectually.", "The lecture ___d several complex aspects of the theory.", ["Darken", "Obfuscate", "Confuse"]),
    ("Inductive", "Characterized by reasoning from specific to general.", "___ reasoning gathers observations to form a theory.", ["Deductive", "Abductive", "Analogical"]),
    ("Juxtaposition", "The fact of placing two things together for contrast.", "The ___ of luxury and poverty in the city was stark.", ["Separation", "Isolation", "Harmony"]),
    ("Legitimacy", "Conformity to the law or to rules; validity.", "The court questioned the ___ of the contract.", ["Illegality", "Invalidity", "Fraudulence"]),
    ("Mutable", "Liable to change; subject to alteration.", "Language is ___ and evolves with culture.", ["Immutable", "Fixed", "Permanent"]),
    ("Normative", "Establishing or relating to a standard.", "___ ethics prescribes how people ought to behave.", ["Descriptive", "Empirical", "Positive"]),
    ("Permeable", "Allowing liquids or gases to pass through.", "The ___ membrane allowed water molecules to pass.", ["Impermeable", "Waterproof", "Sealed"]),
    ("Quantify", "To express or measure the quantity of something.", "It is difficult to ___ the impact of the policy.", ["Qualify", "Describe", "Ignore"]),
    ("Substantiate", "To provide evidence to support a claim.", "The researcher must ___ the findings with data.", ["Refute", "Disprove", "Contradict"]),
    ("Synthesize", "To combine elements into a coherent whole.", "The study ___s data from multiple sources.", ["Analyze", "Separate", "Break down"]),
    ("Transcend", "To go beyond the limits of something.", "Great art ___s cultural and temporal boundaries.", ["Remain within", "Conform", "Submit"]),
    ("Validity", "The quality of being logically or factually sound.", "The ___ of the experiment was questioned.", ["Invalidity", "Falsity", "Fallacy"]),
    ("Correlation", "A mutual relationship between two variables.", "The study found a strong ___ between exercise and health.", ["Causation", "Independence", "Unrelated"]),
    ("Deductive", "Reasoning from general principles to specific cases.", "___ reasoning guarantees a true conclusion if premises are true.", ["Inductive", "Abductive", "Intuitive"]),
    ("Efficacy", "The ability to produce a desired result.", "The ___ of the treatment was proven in clinical trials.", ["Ineffectiveness", "Failure", "Weakness"]),
    ("Heterogeneous", "Diverse in character or content.", "The ___ group included people from twelve countries.", ["Homogeneous", "Uniform", "Similar"]),
    ("Homogeneous", "Of the same kind; uniform in structure.", "The population was surprisingly ___ in its views.", ["Diverse", "Heterogeneous", "Varied"]),
    ("Interdisciplinary", "Involving two or more academic disciplines.", "The ___ program combined biology and computer science.", ["Specialized", "Narrow", "Isolated"]),
    ("Longitudinal", "Running over a long period; measuring change over time.", "The ___ study tracked participants for thirty years.", ["Cross-sectional", "Snapshot", "Brief"]),
    ("Qualitative", "Relating to quality or character, not quantity.", "___ research explores motivations and experiences.", ["Quantitative", "Statistical", "Numerical"]),
    ("Quantitative", "Relating to quantity; measured by numbers.", "___ data was collected through surveys.", ["Qualitative", "Descriptive", "Subjective"]),
    ("Stochastic", "Having a random probability distribution.", "___ models account for uncertainty in predictions.", ["Deterministic", "Predictable", "Fixed"]),
    ("Triangulation", "The use of multiple methods to enhance validity.", "Methodological ___ strengthens research findings.", ["Simplification", "Reduction", "Narrowing"]),
    ("Variance", "The state of being different or divergent.", "There was considerable ___ in the test results.", ["Uniformity", "Consistency", "Sameness"]),
    ("Algorithm", "A process or set of rules for calculations.", "The ___ sorts data in logarithmic time.", ["Random guess", "Intuition", "Heuristic"]),
    ("Boolean", "Relating to a binary system of true or false.", "___ logic underpins all digital computing.", ["Fuzzy", "Continuous", "Analog"]),
    ("Encryption", "The process of encoding information securely.", "End-to-end ___ protects user messages.", ["Decryption", "Plaintext", "Exposure"]),
    ("Theoretical", "Concerned with abstract knowledge rather than practical.", "The ___ framework underpins the experimental design.", ["Applied", "Practical", "Empirical"]),
    ("Abstract", "Existing in thought rather than material form.", "The concept of justice is highly ___.", ["Concrete", "Tangible", "Physical"]),
    ("Categorical", "Unambiguously explicit and direct.", "The evidence provided ___ proof of his innocence.", ["Ambiguous", "Tentative", "Conditional"]),
    ("Conclusive", "Settling a question decisively.", "The DNA test provided ___ evidence.", ["Inconclusive", "Tentative", "Debatable"]),
    ("Derivative", "Imitative of another's work; not original.", "The film felt ___ of better movies.", ["Original", "Innovative", "Novel"]),
    ("Falsifiable", "Capable of being proved false by evidence.", "A scientific theory must be ___.", ["Unfalsifiable", "Dogmatic", "Absolute"]),
    ("Generalize", "To make a broad statement from specific cases.", "It is dangerous to ___ from a single example.", ["Specify", "Detail", "Particularize"]),
    ("Idiosyncratic", "Peculiar to an individual; distinctive.", "His ___ writing style sets him apart.", ["Common", "Universal", "Typical"]),
    ("Neuroscience", "The study of the nervous system and brain.", "Advances in ___ have transformed treatments for depression.", ["Psychology", "Psychiatry", "Biology"]),
    ("Semantics", "The meaning of words and sentences in language.", "The argument was purely about ___ rather than substance.", ["Syntax", "Phonetics", "Pragmatics"]),
    ("Variable", "An element that can change or vary.", "Temperature was a controlled ___ in the experiment.", ["Constant", "Fixed", "Invariable"]),
    ("Bias", "Prejudice in favor or against one thing.", "The study was criticized for confirmation ___.", ["Objectivity", "Neutrality", "Fairness"]),
    ("Consensus", "General agreement among a group.", "The scientific ___ supports the theory of evolution.", ["Disagreement", "Controversy", "Division"]),
    ("Discrete", "Individually separate and distinct.", "The data was divided into ___ categories.", ["Continuous", "Overlapping", "Merged"]),
    ("Endogenous", "Originating from within an organism or system.", "___ growth factors regulate cell development.", ["Exogenous", "External", "Foreign"]),
    ("Exogenous", "Originating from outside an organism or system.", "___ factors like pollution affect health.", ["Endogenous", "Internal", "Innate"]),
    ("Homologous", "Having the same relation or relative position.", "The bat wing and human arm are ___ structures.", ["Analogous", "Different", "Unrelated"]),
    ("Metabolism", "The chemical processes in a living organism.", "Exercise boosts your ___.", ["Digestion", "Respiration", "Circulation"]),
    ("Monopoly", "Exclusive control of a market by one supplier.", "The utility company operated as a government ___.", ["Oligopoly", "Competition", "Free market"]),
    ("Algorithmic", "Relating to a step-by-step problem-solving process.", "___ trading executes orders automatically based on rules.", ["Random", "Intuitive", "Manual"]),
    ("Incremental", "Increasing gradually in regular steps.", "The company focused on ___ improvements rather than radical changes.", ["Dramatic", "Revolutionary", "Exponential"]),
    ("Linear", "Arranged in a straight line; sequential.", "The narrative follows a ___ timeline.", ["Nonlinear", "Circular", "Random"]),
    ("Nonlinear", "Not following a straight or predictable path.", "The relationship between stress and performance is ___.", ["Linear", "Direct", "Straight"]),
    ("Replicate", "To duplicate or reproduce results.", "Other labs failed to ___ the experiment's results.", ["Contradict", "Disprove", "Innovate"]),
    ("Statistical", "Relating to the analysis of numerical data.", "___ significance does not always imply practical importance.", ["Anecdotal", "Qualitative", "Subjective"]),
    ("Causality", "The relationship between cause and effect.", "Correlation does not imply ___.", ["Randomness", "Coincidence", "Independence"]),
    ("Multifaceted", "Having many different aspects or features.", "The issue is ___ and requires a comprehensive approach.", ["Simple", "Unidimensional", "Narrow"]),
    ("Reciprocal", "Given or done in return; mutual.", "The two countries have ___ trade agreements.", ["Unilateral", "One-sided", "Competitive"]),
    ("Verbatim", "In exactly the same words; word for word.", "The transcript reproduced the speech ___.", ["Paraphrased", "Summarized", "Edited"]),
    ("Circumstantial", "Indirect; based on circumstances rather than direct evidence.", "The case relied heavily on ___ evidence.", ["Direct", "Conclusive", "Definitive"]),
    ("Introspective", "Examining one's own thoughts and feelings.", "Her ___ nature led her to keep a detailed journal.", ["Extroverted", "Outward-looking", "Unreflective"]),
    ("Prosaic", "Having the qualities of prose; dull and ordinary.", "The ___ reality of office life disappointed him.", ["Poetic", "Extraordinary", "Romantic"]),
    ("Retrospective", "Looking back on past events or situations.", "A ___ analysis revealed several missed opportunities.", ["Prospective", "Contemporary", "Immediate"]),
    ("Nullify", "To make legally null and void; cancel.", "The court ___d the contract due to fraud.", ["Validate", "Enforce", "Uphold"]),
    ("Unilateral", "Done or undertaken by only one party.", "The ___ decision angered the other partners.", ["Multilateral", "Bilateral", "Collaborative"]),
    ("Ambivalent", "Having mixed feelings about something.", "She felt ___ about leaving her hometown.", ["Certain", "Decided", "Committed"]),
    ("Conspicuous", "Standing out so as to be clearly visible.", "His red car was ___ in the parking lot.", ["Inconspicuous", "Hidden", "Subtle"]),
    ("Contingent", "Dependent on something else; conditional.", "The job offer was ___ on passing a background check.", ["Independent", "Guaranteed", "Absolute"]),
    ("Divergent", "Tending to be different or develop in different directions.", "The siblings had ___ career paths.", ["Convergent", "Similar", "Parallel"]),
    ("Exemplary", "Serving as a desirable model; very good.", "Her ___ conduct earned her a promotion.", ["Mediocre", "Poor", "Substandard"]),
    ("Exhaustive", "Covering all possibilities; thorough.", "The ___ study examined every known variable.", ["Incomplete", "Superficial", "Partial"]),
    ("Explicit", "Stated clearly with no room for confusion.", "The instructions were ___ and easy to follow.", ["Vague", "Ambiguous", "Implicit"]),
    ("Feasible", "Possible and practical to achieve.", "The plan is financially ___.", ["Impossible", "Impractical", "Unworkable"]),
    ("Implicit", "Implied though not directly expressed.", "There was an ___ understanding between them.", ["Explicit", "Clear", "Stated"]),
    ("Inherent", "Existing as a natural or essential part.", "The risks are ___ in the job.", ["Extrinsic", "External", "Acquired"]),
    ("Intrinsic", "Belonging naturally to something; essential.", "The ___ value of art is subjective.", ["Extrinsic", "External", "Surface"]),
    ("Marginal", "Relatively small; of secondary importance.", "The change had only a ___ effect on profits.", ["Significant", "Substantial", "Major"]),
    ("Optimal", "Best or most favorable under the circumstances.", "The ___ solution balances cost and quality.", ["Worst", "Inferior", "Suboptimal"]),
    ("Plausible", "Seeming reasonable or probable.", "The explanation sounds ___ but needs evidence.", ["Implausible", "Unlikely", "Incredible"]),
    ("Potent", "Having great power or effect.", "The ___ drug had severe side effects.", ["Weak", "Mild", "Ineffective"]),
    ("Prevalent", "Widespread in a particular area or time.", "The custom is ___ in rural communities.", ["Rare", "Uncommon", "Scarce"]),
    ("Protracted", "Lasting for a long time; extended.", "The ___ negotiation exhausted both parties.", ["Brief", "Short", "Quick"]),
    ("Provincial", "Of or concerning a province; narrow-minded.", "His ___ outlook limited his career prospects.", ["Cosmopolitan", "Worldly", "Sophisticated"]),
    ("Recondite", "Little known; abstruse.", "The professor specialized in ___ areas of medieval history.", ["Well-known", "Popular", "Obvious"]),
    ("Stringent", "Strict, precise, and exacting.", "The ___ regulations ensured product safety.", ["Lax", "Lenient", "Relaxed"]),
    ("Systemic", "Relating to an entire system; widespread.", "The problem is ___ and affects all departments.", ["Localized", "Isolated", "Minor"]),
    ("Underscore", "To emphasize or stress.", "The incident ___s the need for better security.", ["Understate", "De-emphasize", "Ignore"]),
    ("Viable", "Capable of working successfully; feasible.", "The startup presented a ___ business model.", ["Unworkable", "Impractical", "Dead"]),
    ("Visceral", "Relating to deep inner feelings; instinctive.", "The film evoked a ___ response from audiences.", ["Intellectual", "Rational", "Detached"]),
    ("Zeitgeist", "The defining spirit or mood of a particular era.", "The rise of AI reflects the current technological ___.", ["Tradition", "History", "Past"]),
    ("Aesthetic", "Concerned with beauty or the appreciation of beauty.", "The ___ value of the painting transcended its monetary worth.", ["Functional", "Utilitarian", "Practical"]),
    ("Canonical", "Conforming to a general rule or standard.", "The ___ text serves as the authoritative reference in the field.", ["Atypical", "Apocryphal", "Heterodox"]),
    ("Anomalous", "Deviating from standard or normal patterns.", "The ___ results could not be explained by the current theory.", ["Typical", "Expected", "Normal"]),
    ("Conjectural", "Based on guesswork rather than solid evidence.", "The timeline remains ___ due to lack of records.", ["Definitive", "Conclusive", "Certain"]),
    ("Interpolate", "To insert something between fixed points.", "The editor ___d a clarifying sentence into the paragraph.", ["Extract", "Remove", "Delete"]),
    ("Ostensible", "Seeming true but not necessarily so.", "His ___ enthusiasm masked deep reluctance.", ["Genuine", "Sincere", "Real"]),
    ("Teleological", "Relating to design or purpose in natural phenomena.", "___ explanations attribute events to their ultimate goals.", ["Causal", "Mechanical", "Random"]),
    ("Bifurcate", "To divide into two branches or parts.", "The river ___s into two streams near the delta.", ["Unify", "Merge", "Converge"]),
    ("Generative", "Relating to the production of something.", "The ___ model created new images from text prompts.", ["Destructive", "Consumptive", "Terminal"]),
    ("Oscillation", "Movement back and forth at a regular speed.", "The ___ of the pendulum is a classic physics concept.", ["Stagnation", "Stillness", "Stability"]),
    ("Recursive", "Characterized by recurrence or repetition.", "The ___ function calls itself until a condition is met.", ["Linear", "Progressive", "Sequential"]),
    ("Abductive", "Reasoning from observations to the best explanation.", "___ reasoning is commonly used in medical diagnosis.", ["Deductive", "Inductive", "Analogical"]),
    ("Multivariate", "Involving multiple variables in analysis.", "___ analysis examined all factors simultaneously.", ["Univariate", "Simplistic", "Single"]),
    ("Orthogonal", "Independent or unrelated; at right angles.", "The two issues are ___ and should be addressed separately.", ["Connected", "Related", "Intertwined"]),
    ("Cache", "A storage layer for temporary data.", "The browser ___ stores frequently accessed pages.", ["Delete", "Clear", "Disk"]),
]

# Deck 3: Rare / Obscure
WORDS_DECK_3 = [
    ("Sesquipedalian", "Given to using long words; relating to long words.", "His ___ style made the simple speech incomprehensible.", ["Succinct", "Laconic", "Terse"]),
    ("Ineffable", "Too great or extreme to be expressed in words.", "The beauty of the night sky was ___.", ["Expressible", "Mundane", "Ordinary"]),
    ("Defenestration", "The act of throwing someone out of a window.", "The ___ of the ambassador caused a diplomatic crisis.", ["Elevation", "Entry", "Reception"]),
    ("Petrichor", "A pleasant smell after rain on dry ground.", "The ___ after the storm was refreshing.", ["Stench", "Odor", "Pollution"]),
    ("Clinomania", "An excessive desire to stay in bed.", "Her ___ made her chronically late for work.", ["Insomnia", "Energy", "Hyperactivity"]),
    ("Somnambulist", "A person who walks in their sleep.", "The ___ wandered into the kitchen without waking.", ["Insomniac", "Dreamer", "Hypnotist"]),
    ("Absquatulate", "To leave abruptly; to abscond.", "The treasurer ___d with the company funds.", ["Remain", "Return", "Arrive"]),
    ("Borborygmus", "A rumbling sound in the stomach caused by gas.", "The ___ during the exam was embarrassingly loud.", ["Silence", "Stillness", "Quiet"]),
    ("Cachinnate", "To laugh loudly or immoderately.", "The comedian made the audience ___ uncontrollably.", ["Weep", "Frown", "Sigh"]),
    ("Dysania", "Difficulty waking up and getting out of bed.", "His chronic ___ made mornings a struggle.", ["Insomnia", "Alertness", "Energy"]),
    ("Epeolatry", "The worship of words.", "The poet's ___ bordered on obsession.", ["Logophobia", "Silence", "Aphasia"]),
    ("Fribble", "To waste time trifling or acting foolishly.", "Stop ___ing and get to work.", ["Focus", "Labor", "Strive"]),
    ("Harridan", "A strict, bossy, or belligerent old woman.", "The ___ berated the children for making noise.", ["Sweetheart", "Angel", "Gentle"]),
    ("Jactitation", "A false boast or claim intended to harm someone.", "The lawsuit was based on ___ of marriage.", ["Truth", "Fact", "Modesty"]),
    ("Kakistocracy", "Government by the least suitable or most unscrupulous citizens.", "The regime was a ___ where corruption thrived.", ["Meritocracy", "Aristocracy", "Democracy"]),
    ("Lalochezia", "The use of abusive language to relieve stress.", "He resorted to ___ when stuck in traffic.", ["Silence", "Meditation", "Calm"]),
    ("Maledictory", "Relating to a curse or expressing a wish of evil.", "The ___ inscription warned trespassers of doom.", ["Blessing", "Benedictory", "Praise"]),
    ("Nudiustertian", "Relating to the day before yesterday.", "The ___ news was already outdated.", ["Yesterday", "Today", "Tomorrow"]),
    ("Omphaloskepsis", "Contemplation of one's navel; excessive introspection.", "His ___ prevented any decisive action.", ["Action", "Movement", "Progress"]),
    ("Parrhesia", "The act of speaking candidly or boldly.", "The whistleblower's ___ cost him his job.", ["Silence", "Deception", "Flattery"]),
    ("Recrudescence", "A renewed outbreak after a period of inactivity.", "The ___ of the disease alarmed health officials.", ["Remission", "Cessation", "Decline"]),
    ("Tatterdemalion", "A person dressed in ragged clothing.", "The ___ begged on the street corner.", ["Dandy", "Aristocrat", "Gentleman"]),
    ("Ulotrichous", "Having woolly or tightly curled hair.", "The statue depicted an ___ figure from ancient Africa.", ["Straight-haired", "Bald", "Smooth"]),
    ("Vellichor", "The strange wistfulness of used bookstores.", "She felt ___ while browsing the dusty shelves.", ["Excitement", "Joy", "Indifference"]),
    ("Widdershins", "In a direction contrary to the sun's course; counterclockwise.", "The dancers moved ___ around the maypole.", ["Clockwise", "Forward", "Directly"]),
    ("Xenodochy", "Friendliness toward strangers; hospitality.", "The village was known for its ___.", ["Xenophobia", "Hostility", "Coldness"]),
    ("Yonderly", "Mentally or emotionally distant; absent-minded.", "He had a ___ look in his eyes during the meeting.", ["Attentive", "Alert", "Focused"]),
    ("Zabernism", "The misuse of military authority; bullying.", "The officer's ___ was reported to the command.", ["Diplomacy", "Respect", "Civility"]),
    ("Acedia", "Spiritual or mental sloth; apathy.", "The monk struggled with ___ in the monastery.", ["Zeal", "Passion", "Diligence"]),
    ("Callipygian", "Having well-shaped buttocks.", "The sculpture was celebrated for its ___ proportions.", ["Fragile", "Shapeless", "Bony"]),
    ("Deipnosophist", "A skilled conversationalist at the dinner table.", "The ___ entertained guests with wit and stories.", ["Glutton", "Hermit", "Mute"]),
    ("Ectomorph", "A person with a lean, slender body type.", "The ___ struggled to gain muscle mass.", ["Endomorph", "Mesomorph", "Muscular"]),
    ("Fabulist", "A liar or a writer of fables.", "The ___ invented elaborate stories about his past.", ["Truth-teller", "Historian", "Realist"]),
    ("Gynotikolobomassophile", "A person who nibbles on earlobes.", "She discovered he was a ___ during their date.", ["Teetotaler", "Ascetic", "Monk"]),
    ("Hedonistic", "Engaged in the pursuit of pleasure.", "The ___ lifestyle left him unfulfilled.", ["Ascetic", "Stoic", "Frugal"]),
    ("Jumentous", "Smelling like horse urine.", "The barn had a ___ odor.", ["Floral", "Fragrant", "Fresh"]),
    ("Lemniscate", "A figure-eight shaped curve or symbol.", "The infinity symbol is a ___.", ["Spiral", "Circle", "Triangle"]),
    ("Mumpsimus", "A stubborn person who clings to old errors.", "The ___ refused to accept the corrected data.", ["Progressive", "Reformer", "Innovator"]),
    ("Nepenthe", "A potion used to induce forgetfulness of pain.", "The drug was a modern ___ for emotional trauma.", ["Stimulant", "Memory", "Reminder"]),
    ("Oneiric", "Relating to dreams or dreaming.", "The film had a surreal, ___ quality.", ["Realistic", "Wakeful", "Concrete"]),
    ("Pandiculation", "The act of stretching and yawning upon waking.", "The cat's ___ was accompanied by a loud purr.", ["Exercise", "Collapse", "Stillness"]),
    ("Snollygoster", "A shrewd, unprincipled person, especially a politician.", "The ___ won the election through manipulation.", ["Statesman", "Sage", "Idealist"]),
    ("Thalassophile", "A lover of the sea and oceans.", "The ___ moved to a coastal town.", ["Hydrophobe", "Arachnophile", "Claustrophile"]),
    ("Uhtceare", "Lying awake before dawn worrying.", "She suffered from ___ before the big exam.", ["Serenity", "Peace", "Relaxation"]),
    ("Vulpine", "Relating to a fox; clever and cunning.", "The detective used ___ tactics to solve the case.", ["Naive", "Honest", "Straightforward"]),
    ("Weltschmerz", "A feeling of melancholy about the state of the world.", "The poet's work was full of ___.", ["Optimism", "Joy", "Contentment"]),
    ("Zetetic", "Proceeding by inquiry; investigative.", "The ___ method involves questioning all assumptions.", ["Dogmatic", "Apathetic", "Indifferent"]),
    ("Agelastic", "Never laughing; humorless.", "The ___ critic found nothing amusing.", ["Jovial", "Mirthful", "Cheerful"]),
    ("Cynanthropy", "The delusion that one is a dog.", "The patient's ___ required psychiatric intervention.", ["Lycanthropy", "Zoophobia", "Xenophilia"]),
    ("Dysphoria", "A state of unease or dissatisfaction with life.", "The patient experienced gender ___.", ["Euphoria", "Contentment", "Pleasure"]),
    ("Ecdysiast", "A striptease performer.", "The ___ performed with theatrical flair.", ["Dancer", "Singer", "Actor"]),
    ("Foudroyant", "Sudden and overwhelming; dazzling.", "The ___ lightning strike split the tree.", ["Gentle", "Gradual", "Mild"]),
    ("Hagiography", "The biography of a saint; idealized biography.", "The biography read more like a ___ than a critical study.", ["Critique", "Expos\u00e9", "Debunking"]),
    ("Idempotent", "Unchanged when multiplied or applied to itself.", "The ___ matrix produced the same result each time.", ["Variable", "Changing", "Dynamic"]),
    ("Lambent", "Glowing or flickering with a soft light.", "The ___ flames danced in the fireplace.", ["Dark", "Dull", "Dim"]),
    ("Malediction", "A magical word or phrase uttered to bring evil.", "The witch cast a ___ on the village.", ["Blessing", "Benediction", "Praise"]),
    ("Noctivagant", "Wandering about at night.", "The ___ couple explored the city after midnight.", ["Diurnal", "Homebound", "Sedentary"]),
    ("Oligarchy", "A government ruled by a small group of people.", "The ___ controlled all major decisions.", ["Democracy", "Anarchy", "Monarchy"]),
    ("Splenetic", "Bad-tempered; spiteful.", "The ___ old man shouted at the children.", ["Cheerful", "Kind", "Good-natured"]),
    ("Terpsichorean", "Relating to dancing.", "The ___ performance captivated the audience.", ["Static", "Motionless", "Musical"]),
    ("Veridical", "Truthful or accurate.", "The ___ account was verified by multiple sources.", ["False", "Fictional", "Deceptive"]),
    ("Xylography", "The art of engraving on wood.", "___ was essential for early printing.", ["Lithography", "Typography", "Photography"]),
    ("Zymurgy", "The study of fermentation processes.", "Brewers rely on ___ to perfect their beer.", ["Chemistry", "Biology", "Physics"]),
    ("Antipathy", "A deep-seated dislike or aversion.", "She felt an ___ toward hypocrisy.", ["Affection", "Sympathy", "Admiration"]),
    ("Diaphanous", "Light, delicate, and translucent.", "The ___ curtains filtered the morning light.", ["Opaque", "Thick", "Coarse"]),
    ("Fugacious", "Tending to disappear quickly; fleeting.", "The ___ beauty of cherry blossoms is celebrated.", ["Enduring", "Permanent", "Persistent"]),
    ("Gelid", "Extremely cold; icy.", "The ___ wind cut through their coats.", ["Warm", "Hot", "Balmy"]),
    ("Hebetude", "Mental dullness; lethargy.", "The heat induced a state of ___.", ["Alertness", "Vigor", "Energetic"]),
    ("Jejune", "Naive, simplistic, and superficial.", "The ___ argument failed to convince anyone.", ["Sophisticated", "Profound", "Mature"]),
    ("Labile", "Liable to change; unstable.", "The patient's mood was highly ___.", ["Stable", "Consistent", "Steady"]),
    ("Opprobrium", "Public disgrace or shame.", "The scandal brought ___ upon the family.", ["Honor", "Glory", "Pride"]),
    ("Pulchritude", "Physical beauty.", "The model was celebrated for her ___.", ["Ugliness", "Plainness", "Deformity"]),
    ("Risible", "Provoking laughter; ridiculous.", "The ___ plot of the comedy had everyone laughing.", ["Tragic", "Serious", "Grave"]),
    ("Truculent", "Eager or quick to argue or fight.", "The ___ customer argued with the manager.", ["Docile", "Peaceful", "Agreeable"]),
    ("Usufruct", "The right to enjoy another's property without owning it.", "The tenant held the ___ of the land.", ["Ownership", "Title", "Possession"]),
    ("Agathist", "A person who believes all things tend toward good.", "The ___ remained optimistic despite the crisis.", ["Pessimist", "Cynic", "Fatalist"]),
    ("Bloviate", "To speak pompously and at length.", "The politician ___d for hours without saying anything.", ["Whisper", "Mumble", "Concede"]),
    ("Caliginous", "Dark, dim, or obscure.", "The ___ forest was impenetrable to light.", ["Bright", "Luminous", "Clear"]),
    ("Epithalamium", "A song or poem celebrating a marriage.", "The poet composed an ___ for the royal wedding.", ["Elegy", "Eulogy", "Lament"]),
    ("Febrile", "Having a fever; characterized by great excitement.", "The ___ atmosphere of the concert was electric.", ["Calm", "Apathetic", "Lethargic"]),
    ("Grandiloquent", "Pompous or extravagant in language.", "The ___ speech was full of empty rhetoric.", ["Humble", "Simple", "Modest"]),
    ("Haptic", "Relating to the sense of touch.", "The ___ feedback made the game feel realistic.", ["Visual", "Auditory", "Olfactory"]),
    ("Katabatic", "Relating to wind moving downward.", "The ___ winds swept down the mountain.", ["Anabatic", "Updraft", "Rising"]),
    ("Lambaste", "To criticize harshly.", "The critics ___d the director's latest film.", ["Praise", "Commend", "Applaud"]),
    ("Macabre", "Disturbing and horrifying because of death.", "The ___ painting depicted skeletons dancing.", ["Cheerful", "Joyful", "Lively"]),
    ("Pernicious", "Having a harmful effect in a gradual way.", "The ___ influence of propaganda erodes democracy.", ["Beneficial", "Helpful", "Wholesome"]),
    ("Susurration", "A whispering or rustling sound.", "The ___ of leaves soothed her.", ["Silence", "Quiet", "Stillness"]),
    ("Vituperate", "To blame or insult in strong language.", "The angry customer ___d the poor service.", ["Praise", "Compliment", "Applaud"]),
    ("Xenophobic", "Having a dislike of people from other countries.", "The ___ rhetoric divided the community.", ["Tolerant", "Accepting", "Cosmopolitan"]),
    ("Cachinnation", "Loud or immoderate laughter.", "The ___ from the comedy club could be heard outside.", ["Silence", "Sob", "Whisper"]),
    ("Frisson", "A sudden strong feeling of excitement.", "A ___ ran through the crowd as the star appeared.", ["Apathy", "Boredom", "Dullness"]),
    ("Gloaming", "Twilight; the time between day and night.", "They walked through the ___ as the stars appeared.", ["Dawn", "Noon", "Midnight"]),
    ("Masticate", "To chew food thoroughly.", "It is important to ___ your food well.", ["Swallow", "Gulp", "Inhale"]),
    ("Nugatory", "Of no value or importance.", "The objections were ___ and dismissed.", ["Significant", "Crucial", "Important"]),
    ("Prolix", "Using too many words; long-winded.", "The ___ speaker put the audience to sleep.", ["Concise", "Terse", "Succinct"]),
    ("Amphibology", "A phrase that is grammatically ambiguous.", "The ___ of the contract led to disputes.", ["Clarity", "Precision", "Exactness"]),
    ("Bourgeon", "To begin to grow or increase rapidly.", "The tech sector ___d in the early 2000s.", ["Decline", "Wither", "Shrink"]),
    ("Dispraise", "Expression of disapproval or criticism.", "The review was full of ___ for the novel.", ["Praise", "Acclaim", "Approval"]),
    ("Exuviate", "To shed a covering; to molt.", "The snake ___d its old skin.", ["Grow", "Expand", "Enlarge"]),
    ("Lacustrine", "Relating to lakes.", "The ___ ecosystem supported diverse species.", ["Marine", "Fluvial", "Terrestrial"]),
]

# Load supplementary words and combine to exactly 1000 per deck
from .word_supplement_1 import EXTRA_1
from .word_supplement_2 import EXTRA_2
from .word_supplement_3 import EXTRA_3

# Combine all base words first, ensuring no cross-deck duplicates
_all_base = {}
for d, wlist in [(1, WORDS_DECK_1), (2, WORDS_DECK_2), (3, WORDS_DECK_3)]:
    for w in wlist:
        _all_base.setdefault(w[0].lower(), []).append((d, w))

# Resolve conflicts: keep word in the deck where it first appears
_seen_global = set()
WORDS_DECK_1 = []
WORDS_DECK_2 = []
WORDS_DECK_3 = []
_for_deck = {1: WORDS_DECK_1, 2: WORDS_DECK_2, 3: WORDS_DECK_3}

for deck_id in range(1, 4):
    for w in _all_base.values():
        for d, entry in w:
            if d == deck_id and entry[0].lower() not in _seen_global:
                _for_deck[deck_id].append(entry)
                _seen_global.add(entry[0].lower())
                break

# Now fill each deck to 1000 from supplements
_deck_extras = {1: EXTRA_1, 2: EXTRA_2, 3: EXTRA_3}
for deck_id in [1, 2, 3]:
    target_list = _for_deck[deck_id]
    for w in _deck_extras[deck_id]:
        if w[0].lower() not in _seen_global and len(target_list) < 1000:
            target_list.append(w)
            _seen_global.add(w[0].lower())

WORDS_DECK_1 = WORDS_DECK_1[:1000]
WORDS_DECK_2 = WORDS_DECK_2[:1000]
WORDS_DECK_3 = WORDS_DECK_3[:1000]

# If any deck is short, pad with these extras
if len(WORDS_DECK_2) < 1000:
    _pad_2 = [
        ("Dialectical", "Relating to the logical discussion of ideas and opinions.", "The ___ method involves thesis, antithesis, and synthesis.", ["Dogmatic", "Empirical", "Abstract"]),
        ("Phylogenetic", "Relating to the evolutionary development of a species.", "___ analysis traces the ancestry of organisms.", ["Metabolic", "Genetic", "Cellular"]),
        ("Semiotic", "Relating to signs and symbols and their use.", "___ analysis decodes cultural symbols and meanings.", ["Linguistic", "Phonetic", "Visual"]),
        ("Hermeneutic", "Concerning the interpretation of texts.", "The ___ approach examines biblical passages in context.", ["Literal", "Dogmatic", "Empirical"]),
        ("Synchronic", "Concerned with events at a single point in time.", "A ___ analysis compares languages at the same historical moment.", ["Diachronic", "Historical", "Temporal"]),
        ("Diachronic", "Concerned with how things develop over time.", "A ___ study traced the evolution of the language.", ["Synchronic", "Static", "Fixed"]),
        ("Homiletic", "Relating to preaching or sermons.", "The ___ tradition emphasizes moral lessons from scripture.", ["Liturgical", "Sacramental", "Scriptural"]),
        ("Soteriological", "Relating to the doctrine of salvation.", "The ___ debate centered on faith versus works.", ["Eschatological", "Cosmological", "Ontological"]),
        ("Epiphenomenon", "A secondary phenomenon accompanying another.", "Consciousness may be an ___ of brain activity.", ["Cause", "Origin", "Foundation"]),
        ("Noetic", "Relating to mental activity or intellect.", "The ___ experience transcended ordinary thought.", ["Physical", "Material", "Bodily"]),
    ]
    for w in _pad_2:
        if w[0].lower() not in _seen_global and len(WORDS_DECK_2) < 1000:
            WORDS_DECK_2.append(w)
            _seen_global.add(w[0].lower())
